### ISSUE TITLE
Error running test-server tests

### ISSUE THREAD

**Issue by apmanol** [actix/actix-web#1020]
Hello all,

just need a help tip where to look for the error. In an embedded system with linux  the tests for `test-server` fail all, except the first. If the tests are run one by one manually, they succeed. 

```
--- test_body_br_streaming stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Connect(Resolver(ResolveError { inner: stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new::h552f9d5294b072de (0x56f5936c)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44
   1: failure::backtrace::Backtrace::new::h7d11042c78ab69a9 (0x56f58fd4)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111
   2: failure::context::Context<D>::new::hea57bf68ec337b91 (0x56d21b50)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/context.rs:84
   3: <trust_dns_resolver::error::ResolveError as core::convert::From<trust_dns_resolver::error::ResolveErrorKind>>::from::hc5db6cc259e048f3 (0x56d2b050)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.11.1/src/error.rs:112
   4: <T as core::convert::Into<U>>::into::h50309dee2aea33d3 (0x56d29324)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/convert.rs:540
   5: <trust_dns_resolver::async_resolver::Background<F,G> as core::convert::From<E>>::from::h925d42c99e994645 (0x565ea034)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.11.1/src/async_resolver/mod.rs:358
   6: <T as core::convert::Into<U>>::into::hd8990d8f9c4acbe8 (0x56599b70)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/convert.rs:540
   7: trust_dns_resolver::async_resolver::AsyncResolver::lookup_ip::h48ec943bc6011439 (0x565ea400)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.11.1/src/async_resolver/mod.rs:270
   8: actix_connect::resolver::ResolverFuture<T>::new::h07842d2b31e8867f (0x56562b44)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-connect-0.2.2/src/resolver.rs:137
   9: <actix_connect::resolver::Resolver<T> as actix_service::Service>::call::h28f5408177087a4a (0x5656342c)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-connect-0.2.2/src/resolver.rs:121
  10: <actix_service::and_then::AndThen<A,B> as actix_service::Service>::call::ha5bb79a7ddad09ca (0x565e2ee8)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-0.4.1/src/and_then.rs:58
  11: actix_http::client::connector::Connector<T,U>::finish::{{closure}}::h0ddb7caa99ef7e80 (0x56564fbc)
             at /tmp/actix-web/actix-http/src/client/connector.rs:221
  12: <actix_service::apply::Apply<T,F,In,Out> as actix_service::Service>::call::h369220f753df1f5e (0x565d0984)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-0.4.1/src/apply.rs:90
  13: <actix_service::map_err::MapErr<A,F,E> as actix_service::Service>::call::h922b4164b6f1bcf7 (0x56557ebc)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-0.4.1/src/map_err.rs:61
  14: <actix_service::map::Map<A,F,Response> as actix_service::Service>::call::h230ee96cca714dcb (0x565d7130)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-0.4.1/src/map.rs:60
  15: <actix_utils::timeout::TimeoutService<S> as actix_service::Service>::call::he3029328d6d9048d (0x565f38fc)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-utils-0.4.5/src/timeout.rs:139
  16: <actix_service::map_err::MapErr<A,F,E> as actix_service::Service>::call::h4bb5715877eb161e (0x56557d58)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-0.4.1/src/map_err.rs:61
  17: <actix_http::client::pool::ConnectionPool<T,Io> as actix_service::Service>::call::h9ddafd62bc068ed4 (0x5650a218)
             at /tmp/actix-web/actix-http/src/client/pool.rs:131
  18: <actix_http::client::connector::connect_impl::InnerConnector<T,Io> as actix_service::Service>::call::hbd7ce2c159cc6819 (0x565ebe3c)
             at /tmp/actix-web/actix-http/src/client/connector.rs:393
  19: <awc::connect::ConnectorWrapper<T> as awc::connect::Connect>::send_request::hb086ec92820a4898 (0x56578778)
             at awc/src/connect.rs:54
  20: awc::request::ClientRequest::send_body::h672c41f6b0104fa3 (0x5655ebc0)
             at awc/src/request.rs:445
  21: awc::request::ClientRequest::send::h4eaba264645af746 (0x565c1288)
             at awc/src/request.rs:538
  22: test_server::test_body_br_streaming::hb932c735e89e65c4 (0x562cbc44)
             at tests/test_server.rs:322
  23: test_server::test_body_br_streaming::{{closure}}::h76b3059ba6144af6 (0x562a9454)
             at tests/test_server.rs:310
  24: core::ops::function::FnOnce::call_once::h28e92c32ea0c5afc (0x56328e34)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
  25: core::ops::function::FnOnce::call_once::h0f02361325641ec7 (0x564225ec)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
      test::__rust_begin_short_backtrace::h09121bee50e39adf
             at src/libtest/lib.rs:1522
  26: test::run_test::{{closure}}::h764761cb954b08a0 (0x563f9940)
             at src/libtest/lib.rs:1513
      core::ops::function::FnOnce::call_once::hff9df11e8e147e95
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
      core::ops::function::FnOnce::call_once{{vtable.shim}}::hde82bf5169fd91ad
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
  27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h6b004fa8f4fc1608 (0x56404354)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
  28: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h1d8e99138e9f353e (0x563f8f78)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:315
      std::panicking::try::do_call::h3488c47bf2d2513a
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:293
  29: __rust_maybe_catch_panic (0x57307ee4)
             at src/libpanic_unwind/lib.rs:85
  30: std::panicking::try::h3c78124939494234 (0x56421af0)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:272
      std::panic::catch_unwind::h5d300d705ba1e9d0
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:394
      test::run_test::run_test_inner::{{closure}}::h156c613541bc6a5d
             at src/libtest/lib.rs:1468
  31: test::run_test::run_test_inner::h9eca202717d70a26 (0x564211d0)
             at src/libtest/lib.rs:1490
  32: test::run_test::hbd8ccbd81fdda88c (0x5641f8a0)
             at src/libtest/lib.rs:1509
  33: test::run_tests::hcf8b8a4e4e83354e (0x56417b1c)
             at src/libtest/lib.rs:1168
      test::run_tests_console::h59f52ba90f617ae0
             at src/libtest/lib.rs:973
  34: test::test_main::h1d6ff03d80615ce9 (0x5640f628)
             at src/libtest/lib.rs:294
  35: test::test_main_static::h5279b0fa73db22f4 (0x5640ff5c)
             at src/libtest/lib.rs:328
  36: test_server::main::h0dc9b5d8b6890160 (0x562d3410)
  37: std::rt::lang_start::{{closure}}::he284e60fc41e1a10 (0x560db48c)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  38: std::rt::lang_start_internal::{{closure}}::{{closure}}::h3a28733b62d1787b (0x572fe030)
             at src/libstd/rt.rs:49
      std::sys_common::backtrace::__rust_begin_short_backtrace::he5b70b115bfee956
             at src/libstd/sys_common/backtrace.rs:136
  39: std::rt::lang_start_internal::{{closure}}::h2ecb227ea5d9e617 (0x573014c4)
             at src/libstd/rt.rs:49
      std::panicking::try::do_call::hf0d794f61386f00a
             at src/libstd/panicking.rs:293
  40: __rust_maybe_catch_panic (0x57307ee4)
             at src/libpanic_unwind/lib.rs:85
  41: std::panicking::try::h0870cd8f44db63cb (0x573022e4)
             at src/libstd/panicking.rs:272
      std::panic::catch_unwind::hb1164a9f02595c53
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal::h2e68240ef81cd52f
             at src/libstd/rt.rs:48
  42: std::rt::lang_start::h641764d36bf5a0c1 (0x560db448)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  43: main (0x562d346c)
  44: __libc_start_main (0x779091c8)
  45: <unknown> (0x5609dc3c)


RUST_BACKTRACE=1    RUST_LOG=debug  ./test_server-5d1b6b57988c69f2  test_brotli -- --no-capture 

running 2 tests
test test_brotli_encoding ... ok
test test_brotli_encoding_large ... FAILED

failures:

---- test_brotli_encoding_large stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Connect(Resolver(ResolveError { inner: stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new::h552f9d5294b072de (0x57916470)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44
   1: failure::backtrace::Backtrace::new::h7d11042c78ab69a9 (0x579160d8)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111
   2: failure::context::Context<D>::new::hea57bf68ec337b91 (0x576dec54)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/context.rs:84
   3: <trust_dns_resolver::error::ResolveError as core::convert::From<trust_dns_resolver::error::ResolveErrorKind>>::from::hc5db6cc259e048f3 (0x576e8154)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.11.1/src/error.rs:112
   4: <T as core::convert::Into<U>>::into::h50309dee2aea33d3 (0x576e6428)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/convert.rs:540
   5: <trust_dns_resolver::async_resolver::Background<F,G> as core::convert::From<E>>::from::h925d42c99e994645 (0x56f9d230)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.11.1/src/async_resolver/mod.rs:358
   6: <T as core::convert::Into<U>>::into::hd8990d8f9c4acbe8 (0x56f4cd6c)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/convert.rs:540
   7: trust_dns_resolver::async_resolver::AsyncResolver::lookup_ip::h48ec943bc6011439 (0x56f9d5fc)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.11.1/src/async_resolver/mod.rs:270
   8: actix_connect::resolver::ResolverFuture<T>::new::h07842d2b31e8867f (0x56f15d40)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-connect-0.2.2/src/resolver.rs:137
   9: <actix_connect::resolver::Resolver<T> as actix_service::Service>::call::h28f5408177087a4a (0x56f16628)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-connect-0.2.2/src/resolver.rs:121
  10: <actix_service::and_then::AndThen<A,B> as actix_service::Service>::call::ha5bb79a7ddad09ca (0x56f960e4)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-0.4.1/src/and_then.rs:58
  11: actix_http::client::connector::Connector<T,U>::finish::{{closure}}::h0ddb7caa99ef7e80 (0x56f181b8)
             at /tmp/actix-web/actix-http/src/client/connector.rs:221
  12: <actix_service::apply::Apply<T,F,In,Out> as actix_service::Service>::call::h369220f753df1f5e (0x56f83b80)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-0.4.1/src/apply.rs:90
  13: <actix_service::map_err::MapErr<A,F,E> as actix_service::Service>::call::h922b4164b6f1bcf7 (0x56f0b0b8)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-0.4.1/src/map_err.rs:61
  14: <actix_service::map::Map<A,F,Response> as actix_service::Service>::call::h230ee96cca714dcb (0x56f8a32c)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-0.4.1/src/map.rs:60
  15: <actix_utils::timeout::TimeoutService<S> as actix_service::Service>::call::he3029328d6d9048d (0x56fa6af8)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-utils-0.4.5/src/timeout.rs:139
  16: <actix_service::map_err::MapErr<A,F,E> as actix_service::Service>::call::h4bb5715877eb161e (0x56f0af54)
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-0.4.1/src/map_err.rs:61
  17: <actix_http::client::pool::ConnectionPool<T,Io> as actix_service::Service>::call::h9ddafd62bc068ed4 (0x56ebd414)
             at /tmp/actix-web/actix-http/src/client/pool.rs:131
  18: <actix_http::client::connector::connect_impl::InnerConnector<T,Io> as actix_service::Service>::call::hbd7ce2c159cc6819 (0x56f9f038)
             at /tmp/actix-web/actix-http/src/client/connector.rs:393
  19: <awc::connect::ConnectorWrapper<T> as awc::connect::Connect>::send_request::hb086ec92820a4898 (0x56f2b974)
             at awc/src/connect.rs:54
  20: awc::request::ClientRequest::send_body::h587819938a6d95dd (0x56b8abf4)
             at /tmp/actix-web/awc/src/request.rs:445
  21: test_server::test_brotli_encoding_large::h497387cb11ea0b27 (0x56c4bd4c)
             at tests/test_server.rs:715
  22: test_server::test_brotli_encoding_large::{{closure}}::hff6b7b4e14530efa (0x56c2558c)
             at tests/test_server.rs:699
  23: core::ops::function::FnOnce::call_once::h9f75f338a5b7f040 (0x56ca463c)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
  24: core::ops::function::FnOnce::call_once::h0f02361325641ec7 (0x56dd57e8)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
      test::__rust_begin_short_backtrace::h09121bee50e39adf
             at src/libtest/lib.rs:1522
  25: test::run_test::{{closure}}::h764761cb954b08a0 (0x56dacb3c)
             at src/libtest/lib.rs:1513
      core::ops::function::FnOnce::call_once::hff9df11e8e147e95
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
      core::ops::function::FnOnce::call_once{{vtable.shim}}::hde82bf5169fd91ad
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
  26: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h6b004fa8f4fc1608 (0x56db7550)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
  27: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h1d8e99138e9f353e (0x56dac174)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:315
      std::panicking::try::do_call::h3488c47bf2d2513a
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:293
  28: __rust_maybe_catch_panic (0x57cc95cc)
             at src/libpanic_unwind/lib.rs:85
  29: std::panicking::try::h3c78124939494234 (0x56dd4cec)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:272
      std::panic::catch_unwind::h5d300d705ba1e9d0
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:394
      test::run_test::run_test_inner::{{closure}}::h156c613541bc6a5d
             at src/libtest/lib.rs:1468
  30: test::run_test::run_test_inner::h9eca202717d70a26 (0x56dd43cc)
             at src/libtest/lib.rs:1490
  31: test::run_test::hbd8ccbd81fdda88c (0x56dd2a9c)
             at src/libtest/lib.rs:1509
  32: test::run_tests::hcf8b8a4e4e83354e (0x56dcad18)
             at src/libtest/lib.rs:1168
      test::run_tests_console::h59f52ba90f617ae0
             at src/libtest/lib.rs:973
  33: test::test_main::h1d6ff03d80615ce9 (0x56dc2824)
             at src/libtest/lib.rs:294
  34: test::test_main_static::h5279b0fa73db22f4 (0x56dc3158)
             at src/libtest/lib.rs:328
  35: test_server::main::h0dc9b5d8b6890160 (0x56c4c320)
  36: std::rt::lang_start::{{closure}}::he284e60fc41e1a10 (0x56a5410c)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  37: std::rt::lang_start_internal::{{closure}}::{{closure}}::h3a28733b62d1787b (0x57cbf6ec)
             at src/libstd/rt.rs:49
      std::sys_common::backtrace::__rust_begin_short_backtrace::he5b70b115bfee956
             at src/libstd/sys_common/backtrace.rs:136
  38: std::rt::lang_start_internal::{{closure}}::h2ecb227ea5d9e617 (0x57cc2b80)
             at src/libstd/rt.rs:49
      std::panicking::try::do_call::hf0d794f61386f00a
             at src/libstd/panicking.rs:293
  39: __rust_maybe_catch_panic (0x57cc95cc)
             at src/libpanic_unwind/lib.rs:85
  40: std::panicking::try::h0870cd8f44db63cb (0x57cc39a0)
             at src/libstd/panicking.rs:272
      std::panic::catch_unwind::hb1164a9f02595c53
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal::h2e68240ef81cd52f
             at src/libstd/rt.rs:48
  41: std::rt::lang_start::h641764d36bf5a0c1 (0x56a540c8)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  42: main (0x56c4c37c)
  43: __libc_start_main (0x7727a1c8)
  44: <unknown> (0x56a168bc)

background resolver gone, this is a bug }))', src/libcore/result.rs:999:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:208
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::unwrap
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/result.rs:800
  10: test_server::test_brotli_encoding_large
             at tests/test_server.rs:719
  11: test_server::test_brotli_encoding_large::{{closure}}
             at tests/test_server.rs:699
  12: core::ops::function::FnOnce::call_once
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231


failures:
    test_brotli_encoding_large

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 19 filtered out

```

**Comment by fafhrd91** [comment]
same problem as #1007

**Comment by apmanol** [comment]
Thanks for the prompt reply.

**Comment by fafhrd91** [comment]
fixed in actix-connect 0.2.4

**Comment by apmanol** [comment]
with commit: c9400456f665fb30d61031289570aafae01b1b61
I get the following again:

```
# RUST_BACKTRACE=1    RUST_LOG=debug  ./test_server test_body_br    -- --no-capture 

running 2 tests
test test_body_br_streaming ... ok
test test_body_brotli ... FAILED

failures:

---- test_body_brotli stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Connect(Resolver(ResolveError { inner: stack backtrace:
   0: failure::backtrace::Backtrace::new::he35787c56d4c54d7 (0x55bb5b7c)
   1: <trust_dns_resolver::error::ResolveError as core::convert::From<trust_dns_resolver::error::ResolveErrorKind>>::from::h14f5cb200ef63b70 (0x55b16d6c)
   2: trust_dns_resolver::async_resolver::AsyncResolver::lookup_ip::h23b2e5ef7b525df9 (0x5564695c)
   3: <actix_connect::resolver::Resolver<T> as actix_service::Service>::call::he15af3e607ce3639 (0x557e81e8)
   4: <actix_service::map::Map<A,F,Response> as actix_service::Service>::call::h3d386597c068a450 (0x55777f24)
   5: <actix_http::client::pool::ConnectionPool<T,Io> as actix_service::Service>::call::h5bc5980c291b8668 (0x5572f068)
   6: <actix_http::client::connector::connect_impl::InnerConnector<T,Io> as actix_service::Service>::call::h2f9a528433ce8805 (0x55644ab4)
   7: <awc::connect::ConnectorWrapper<T> as awc::connect::Connect>::send_request::h40e679c08edd30ca (0x5578f56c)
   8: awc::request::ClientRequest::send::h4c0b28a224d43cb7 (0x5593cf84)
   9: core::ops::function::FnOnce::call_once::hf20da314539e102c (0x5562f41c)
  10: core::ops::function::FnOnce::call_once::h74bec105eeee42af (0x55866c44)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:231
      test::__rust_begin_short_backtrace::h2a36b69db2bf7c12
             at src/libtest/lib.rs:1520
  11: test::run_test::{{closure}}::h1ea7f375339da71a (0x5583e668)
             at src/libtest/lib.rs:1511
      core::ops::function::FnOnce::call_once{{vtable.shim}}::h0699c18f8d7435f3
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:231
  12: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h4a13ee3f0d7b4201 (0x55848e7c)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  13: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h800ca2efdebd7986 (0x5583dea0)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:315
      std::panicking::try::do_call::h65d54f3c714fa2d5
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:296
  14: __rust_maybe_catch_panic (0x55c5a87c)
             at src/libpanic_unwind/lib.rs:82
  15: std::panicking::try::h000b175710d7e4e5 (0x5586612c)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:275
      std::panic::catch_unwind::h62512aee8dd06cb3
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:394
      test::run_test::run_test_inner::{{closure}}::h0a0f5374532929ed
             at src/libtest/lib.rs:1466
  16: test::run_test::run_test_inner::h9b97c8f699fe8334 (0x5586580c)
             at src/libtest/lib.rs:1488
  17: test::run_test::he0ae8611eaec8328 (0x55863ed4)
             at src/libtest/lib.rs:1507
  18: test::run_tests::hb04296b8ff48097d (0x5585c0f0)
             at src/libtest/lib.rs:1166
      test::run_tests_console::h5107855ba20a9ca1
             at src/libtest/lib.rs:971
  19: test::test_main::hf34346a20cdd49ed (0x558540c8)
             at src/libtest/lib.rs:292
  20: test::test_main_static::h2aec52c3c05b6bb4 (0x558549fc)
             at src/libtest/lib.rs:326
  21: test_server::main::h2e02711ffbecfa87 (0x5564384c)
  22: std::rt::lang_start::{{closure}}::hf29692acb3f3fd19 (0x55735960)
  23: std::rt::lang_start_internal::{{closure}}::{{closure}}::h9f295cf887f8f17b (0x55c509d4)
             at src/libstd/rt.rs:49
      std::sys_common::backtrace::__rust_begin_short_backtrace::hcfc6ba3cb62d0e08
             at src/libstd/sys_common/backtrace.rs:77
  24: std::rt::lang_start_internal::{{closure}}::hc18007f9f4412875 (0x55c548bc)
             at src/libstd/rt.rs:49
      std::panicking::try::do_call::h2777efde8a02dd73
             at src/libstd/panicking.rs:296
  25: __rust_maybe_catch_panic (0x55c5a87c)
             at src/libpanic_unwind/lib.rs:82
  26: std::panicking::try::hcea24ba06de41e38 (0x55c556dc)
             at src/libstd/panicking.rs:275
      std::panic::catch_unwind::hd6f674f11a82e746
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal::h602b7f145abc7776
             at src/libstd/rt.rs:48
  27: std::rt::lang_start::h1e4a745d81e43e07 (0x55735940)
  28: main (0x55643884)
  29: __libc_start_main (0x2ab8908c)

background resolver gone, this is a bug }))', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
  11: core::ops::function::FnOnce::call_once
  12: core::ops::function::FnOnce::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:231
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test_body_brotli

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 19 filtered out


```

**Comment by fafhrd91** [comment]
do you have code published anywhere?

**Comment by apmanol** [comment]
I use the test_server (cargo test) from this repo, nothing more. But the embedded environment is isolated, with no internet access.

**Comment by fafhrd91** [comment]
@apmanol could you create isolated example?

**Comment by apmanol** [comment]
Unfortunately, I can't isolate the issue and it is only observable in a low end CPU.
Is it possible to guide on  where to add some printouts, so as to help debugging? 

Again thanks a lot for your effort!

**Comment by fafhrd91** [comment]
btw did you run `cargo update` before running tests?

**Comment by apmanol** [comment]
> btw did you run `cargo update` before running tests?

Yes many many times just to make sure.
```
 rg actix.connect Cargo.lock 
42:name = "actix-connect"
98: "actix-connect 0.2.5 (registry+https://github.com/rust-lang/crates.io-index)",
117: "actix-connect 0.2.5 (registry+https://github.com/rust-lang/crates.io-index)",
172: "actix-connect 0.2.5 (registry+https://github.com/rust-lang/crates.io-index)",
360: "actix-connect 0.2.5 (registry+https://github.com/rust-lang/crates.io-index)",
2065:"checksum actix-connect 0.2.5 (registry+https://github.com/rust-lang/crates.io-index)" = "9fade9bd4bb46bacde89f1e726c7a3dd230536092712f5d94d77ca57c087fca0"

```

**Comment by fafhrd91** [comment]
@apmanol do you use `actix-http-test` in tests?

**Comment by apmanol** [comment]
> @apmanol do you use `actix-http-test` in tests?
```
$ rg actix-http-test Cargo.lock 
100: "actix-http-test 0.2.4",
118: "actix-http-test 0.2.4",
219:name = "actix-http-test"
413: "actix-http-test 0.2.4",
455: "actix-http-test 0.2.4",
467: "actix-http-test 0.2.4",
522: "actix-http-test 0.2.4",

```

Again with 32a1c365975acffb25959f5887a6530396788504 the issue remains

```
# ./test_server test_body_br  --nocapture 
running 2 tests
test test_body_br_streaming ... ok
test test_body_brotli ... thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Connect(Resolver(ResolveError { inner: 

background resolver gone, this is a bug }))', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
FAILED


failures:
    test_body_brotli
```

**Comment by fafhrd91** [comment]
could you try actix-http-test 0.2.5

**Comment by apmanol** [comment]
Yes it works! Thanks again for your time and your effort!
So it was a problem of the tests and not of the actual code?

**Comment by fafhrd91** [comment]
Problem was in test server
