### ISSUE TITLE
hangs on Windows when there's a panic

### ISSUE THREAD

**Issue by bbigras** [actix/actix-web#1065]
When there's a panic on Windows, the client's connection will hang. This can be confusing for users as they don't get an error message.

It also hangs with async handlers.

It doesn't hang on Linux.

actix-web 1.0.7
nightly-2019-08-01-x86_64-pc-windows-msvc (default)
rustc 1.38.0-nightly (8a58268b5 2019-07-31)

```rust
use actix_web::{web, App, HttpServer, Responder};

fn index() -> impl Responder {
    panic!("test panic");
}

fn main() -> std::io::Result<()> {
    HttpServer::new(|| App::new().service(web::resource("/").to(index)))
        .bind("127.0.0.1:8080")?
        .run()
}
```

```
PS C:\Users\bbigras\dev\actix-panic> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.22s
     Running `target\debug\actix-panic.exe`
thread 'actix-rt:worker:0' panicked at 'test panic', src\main.rs:4:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.34\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/8a58268b5ad9c4a240be349a633069d48991eb0c\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/8a58268b5ad9c4a240be349a633069d48991eb0c\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/8a58268b5ad9c4a240be349a633069d48991eb0c\/src\libstd\panicking.rs:200
   4: std::panicking::default_hook
             at /rustc/8a58268b5ad9c4a240be349a633069d48991eb0c\/src\libstd\panicking.rs:214
   5: std::panicking::rust_panic_with_hook
             at /rustc/8a58268b5ad9c4a240be349a633069d48991eb0c\/src\libstd\panicking.rs:477
   6: std::panicking::begin_panic<str*>
             at /rustc/8a58268b5ad9c4a240be349a633069d48991eb0c\src\libstd\panicking.rs:411
   7: actix_panic::index
             at .\src\main.rs:4
   8: core::ops::function::Fn::call<fn(),()>
             at /rustc/8a58268b5ad9c4a240be349a633069d48991eb0c\src\libcore\ops\function.rs:69
   9: actix_web::handler::{{impl}}::call<fn(),()>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-1.0.7\src\handler.rs:28
  10: actix_web::handler::{{impl}}::call<fn(),(),()>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-1.0.7\src\handler.rs:83
  11: actix_web::handler::{{impl}}::poll<(),actix_web::handler::Handler<fn(), (), ()>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-1.0.7\src\handler.rs:369
  12: actix_web::route::{{impl}}::call<actix_web::handler::ExtractService<(), actix_web::handler::Handler<fn(), (), ()>>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-1.0.7\src\route.rs:364
  13: actix_service::{{impl}}::call<Service>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-service-0.4.2\src\lib.rs:369
  14: actix_web::route::{{impl}}::call
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-1.0.7\src\route.rs:135
  15: actix_web::resource::{{impl}}::call
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-1.0.7\src\resource.rs:558
  16: actix_service::boxed::{{impl}}::call<actix_web::resource::ResourceService,actix_web::service::ServiceRequest,actix_web::service::ServiceResponse<actix_http::body::Body>,actix_http::error::Error>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-service-0.4.2\src\boxed.rs:144
  17: actix_service::{{impl}}::call<Service>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-service-0.4.2\src\lib.rs:369
  18: actix_web::app_service::{{impl}}::call
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-1.0.7\src\app_service.rs:411
  19: actix_web::app_service::{{impl}}::call<actix_web::app_service::AppRouting,actix_http::body::Body>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-1.0.7\src\app_service.rs:255
  20: actix_http::cloneable::{{impl}}::call<actix_web::app_service::AppInitService<actix_web::app_service::AppRouting, actix_http::body::Body>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-http-0.2.9\src\cloneable.rs:40
  21: actix_http::h1::dispatcher::InnerDispatcher<tokio_tcp::stream::TcpStream, actix_web::app_service::AppInitService<actix_web::app_service::AppRouting, actix_http::body::Body>, actix_http::body::Body, actix_http::h1::expect::ExpectHandler, actix_http::h1::up
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-http-0.2.9\src\h1\dispatcher.rs:471
  22: actix_http::h1::dispatcher::InnerDispatcher<tokio_tcp::stream::TcpStream, actix_web::app_service::AppInitService<actix_web::app_service::AppRouting, actix_http::body::Body>, actix_http::body::Body, actix_http::h1::expect::ExpectHandler, actix_http::h1::up
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-http-0.2.9\src\h1\dispatcher.rs:524
  23: actix_http::h1::dispatcher::{{impl}}::poll<tokio_tcp::stream::TcpStream,actix_web::app_service::AppInitService<actix_web::app_service::AppRouting, actix_http::body::Body>,actix_http::body::Body,actix_http::h1::expect::ExpectHandler,actix_http::h1::upgrade
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-http-0.2.9\src\h1\dispatcher.rs:715
  24: actix_http::service::{{impl}}::poll<tokio_tcp::stream::TcpStream,actix_web::app_service::AppInitService<actix_web::app_service::AppRouting, actix_http::body::Body>,actix_http::body::Body,actix_http::h1::expect::ExpectHandler,actix_http::h1::upgrade::Upgra
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-http-0.2.9\src\service.rs:464
  25: actix_http::service::{{impl}}::poll<tokio_tcp::stream::TcpStream,actix_web::app_service::AppInitService<actix_web::app_service::AppRouting, actix_http::body::Body>,actix_http::body::Body,actix_http::h1::expect::ExpectHandler,actix_http::h1::upgrade::Upgra
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-http-0.2.9\src\service.rs:514
  26: futures::future::chain::Chain<actix_http::service::HttpServiceHandlerResponse<tokio_tcp::stream::TcpStream, actix_web::app_service::AppInitService<actix_web::app_service::AppRouting, actix_http::body::Body>, actix_http::body::Body, actix_http::h1::expect:
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.28\src\future\chain.rs:26
  27: futures::future::then::{{impl}}::poll<actix_http::service::HttpServiceHandlerResponse<tokio_tcp::stream::TcpStream, actix_web::app_service::AppInitService<actix_web::app_service::AppRouting, actix_http::body::Body>, actix_http::body::Body, actix_http::h1:
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.28\src\future\then.rs:32
  28: futures::future::{{impl}}::poll<futures::future::then::Then<actix_http::service::HttpServiceHandlerResponse<tokio_tcp::stream::TcpStream, actix_web::app_service::AppInitService<actix_web::app_service::AppRouting, actix_http::body::Body>, actix_http::body:
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.28\src\future\mod.rs:113
  29: futures::future::{{impl}}::poll<Future>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.28\src\future\mod.rs:113
  30: futures::task_impl::{{impl}}::poll_future_notify::{{closure}}<alloc::boxed::Box<Future>,tokio_current_thread::scheduler::Notify<tokio_reactor::Handle>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.28\src\task_impl\mod.rs:329
  31: futures::task_impl::{{impl}}::enter::{{closure}}<alloc::boxed::Box<Future>,closure,core::result::Result<futures::poll::Async<()>, ()>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.28\src\task_impl\mod.rs:399
  32: futures::task_impl::std::set<closure,core::result::Result<futures::poll::Async<()>, ()>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.28\src\task_impl\std\mod.rs:83
  33: futures::task_impl::Spawn<alloc::boxed::Box<Future>>::enter<alloc::boxed::Box<Future>,closure,core::result::Result<futures::poll::Async<()>, ()>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.28\src\task_impl\mod.rs:399
  34: futures::task_impl::Spawn<alloc::boxed::Box<Future>>::poll_fn_notify<alloc::boxed::Box<Future>,tokio_current_thread::scheduler::Notify<tokio_reactor::Handle>,closure,core::result::Result<futures::poll::Async<()>, ()>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.28\src\task_impl\mod.rs:291
  35: futures::task_impl::Spawn<alloc::boxed::Box<Future>>::poll_future_notify<alloc::boxed::Box<Future>,tokio_current_thread::scheduler::Notify<tokio_reactor::Handle>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-0.1.28\src\task_impl\mod.rs:329
  36: tokio_current_thread::scheduler::Scheduled<tokio_reactor::Handle>::tick<tokio_reactor::Handle>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-current-thread-0.1.6\src\scheduler.rs:351
  37: tokio_current_thread::scheduler::{{impl}}::tick::{{closure}}<tokio_reactor::Handle>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-current-thread-0.1.6\src\scheduler.rs:330
  38: tokio_current_thread::{{impl}}::enter::{{closure}}::{{closure}}<tokio_reactor::Handle,closure,bool>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-current-thread-0.1.6\src\lib.rs:788
  39: tokio_current_thread::CurrentRunner::set_spawn<closure,bool>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-current-thread-0.1.6\src\lib.rs:825
  40: tokio_current_thread::{{impl}}::enter::{{closure}}<tokio_reactor::Handle,closure,bool>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-current-thread-0.1.6\src\lib.rs:788
  41: std::thread::local::LocalKey<tokio_current_thread::CurrentRunner>::try_with<tokio_current_thread::CurrentRunner,closure,bool>
             at /rustc/8a58268b5ad9c4a240be349a633069d48991eb0c\src\libstd\thread\local.rs:257
  42: std::thread::local::LocalKey<tokio_current_thread::CurrentRunner>::with<tokio_current_thread::CurrentRunner,closure,bool>
             at /rustc/8a58268b5ad9c4a240be349a633069d48991eb0c\src\libstd\thread\local.rs:234
  43: tokio_current_thread::Borrow<tokio_reactor::Handle>::enter<tokio_reactor::Handle,closure,bool>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-current-thread-0.1.6\src\lib.rs:786
  44: tokio_current_thread::scheduler::Scheduler<tokio_reactor::Handle>::tick<tokio_reactor::Handle>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-current-thread-0.1.6\src\scheduler.rs:330
  45: tokio_current_thread::Entered<tokio_timer::timer::Timer<tokio_reactor::Reactor, tokio_timer::clock::clock::Clock>>::tick<tokio_timer::timer::Timer<tokio_reactor::Reactor, tokio_timer::clock::clock::Clock>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-current-thread-0.1.6\src\lib.rs:612
  46: tokio_current_thread::Entered<tokio_timer::timer::Timer<tokio_reactor::Reactor, tokio_timer::clock::clock::Clock>>::block_on<tokio_timer::timer::Timer<tokio_reactor::Reactor, tokio_timer::clock::clock::Clock>,futures::sync::oneshot::Receiver<i32>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-current-thread-0.1.6\src\lib.rs:502
  47: actix_rt::runtime::{{impl}}::block_on::{{closure}}<futures::sync::oneshot::Receiver<i32>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-rt-0.2.4\src\runtime.rs:128
  48: actix_rt::runtime::{{impl}}::enter::{{closure}}::{{closure}}::{{closure}}::{{closure}}<closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-rt-0.2.4\src\runtime.rs:168
  49: tokio_executor::global::with_default::{{closure}}<tokio_current_thread::TaskExecutor,closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-executor-0.1.8\src\global.rs:209
  50: std::thread::local::LocalKey<core::cell::Cell<tokio_executor::global::State>>::try_with<core::cell::Cell<tokio_executor::global::State>,closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
             at /rustc/8a58268b5ad9c4a240be349a633069d48991eb0c\src\libstd\thread\local.rs:257
  51: std::thread::local::LocalKey<core::cell::Cell<tokio_executor::global::State>>::with<core::cell::Cell<tokio_executor::global::State>,closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
             at /rustc/8a58268b5ad9c4a240be349a633069d48991eb0c\src\libstd\thread\local.rs:234
  52: tokio_executor::global::with_default<tokio_current_thread::TaskExecutor,closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-executor-0.1.8\src\global.rs:178
  53: actix_rt::runtime::{{impl}}::enter::{{closure}}::{{closure}}::{{closure}}<closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-rt-0.2.4\src\runtime.rs:166
  54: tokio_timer::timer::handle::with_default::{{closure}}<closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-timer-0.2.11\src\timer\handle.rs:101
  55: std::thread::local::LocalKey<core::cell::RefCell<core::option::Option<tokio_timer::timer::handle::HandlePriv>>>::try_with<core::cell::RefCell<core::option::Option<tokio_timer::timer::handle::HandlePriv>>,closure,core::result::Result<i32, futures::sync::on
             at /rustc/8a58268b5ad9c4a240be349a633069d48991eb0c\src\libstd\thread\local.rs:257
  56: std::thread::local::LocalKey<core::cell::RefCell<core::option::Option<tokio_timer::timer::handle::HandlePriv>>>::with<core::cell::RefCell<core::option::Option<tokio_timer::timer::handle::HandlePriv>>,closure,core::result::Result<i32, futures::sync::onesho
             at /rustc/8a58268b5ad9c4a240be349a633069d48991eb0c\src\libstd\thread\local.rs:234
  57: tokio_timer::timer::handle::with_default<closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-timer-0.2.11\src\timer\handle.rs:84
  58: actix_rt::runtime::{{impl}}::enter::{{closure}}::{{closure}}<closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-rt-0.2.4\src\runtime.rs:159
  59: tokio_timer::clock::clock::with_default::{{closure}}<closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-timer-0.2.11\src\clock\clock.rs:137
  60: std::thread::local::LocalKey<core::cell::Cell<core::option::Option<const tokio_timer::clock::clock::Clock*>>>::try_with<core::cell::Cell<core::option::Option<const tokio_timer::clock::clock::Clock*>>,closure,core::result::Result<i32, futures::sync::onesho
             at /rustc/8a58268b5ad9c4a240be349a633069d48991eb0c\src\libstd\thread\local.rs:257
  61: std::thread::local::LocalKey<core::cell::Cell<core::option::Option<const tokio_timer::clock::clock::Clock*>>>::with<core::cell::Cell<core::option::Option<const tokio_timer::clock::clock::Clock*>>,closure,core::result::Result<i32, futures::sync::oneshot::C
             at /rustc/8a58268b5ad9c4a240be349a633069d48991eb0c\src\libstd\thread\local.rs:234
  62: tokio_timer::clock::clock::with_default<closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-timer-0.2.11\src\clock\clock.rs:117
  63: actix_rt::runtime::{{impl}}::enter::{{closure}}<closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-rt-0.2.4\src\runtime.rs:158
  64: tokio_reactor::with_default::{{closure}}<closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-reactor-0.1.9\src\lib.rs:237
  65: std::thread::local::LocalKey<core::cell::RefCell<core::option::Option<tokio_reactor::HandlePriv>>>::try_with<core::cell::RefCell<core::option::Option<tokio_reactor::HandlePriv>>,closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
             at /rustc/8a58268b5ad9c4a240be349a633069d48991eb0c\src\libstd\thread\local.rs:257
  66: std::thread::local::LocalKey<core::cell::RefCell<core::option::Option<tokio_reactor::HandlePriv>>>::with<core::cell::RefCell<core::option::Option<tokio_reactor::HandlePriv>>,closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
             at /rustc/8a58268b5ad9c4a240be349a633069d48991eb0c\src\libstd\thread\local.rs:234
  67: tokio_reactor::with_default<closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-reactor-0.1.9\src\lib.rs:217
  68: actix_rt::runtime::Runtime::enter<closure,core::result::Result<i32, futures::sync::oneshot::Canceled>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-rt-0.2.4\src\runtime.rs:157
  69: actix_rt::runtime::Runtime::block_on<futures::sync::oneshot::Receiver<i32>>
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-rt-0.2.4\src\runtime.rs:126
  70: actix_rt::arbiter::{{impl}}::new::{{closure}}
             at C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-rt-0.2.4\src\arbiter.rs:109
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic in Arbiter thread, shutting down system.
```

**Comment by robjtede** [comment]
closing issue due to age.
if this is still an issue, feel free to open a new issue in the context of newer actix web versions
