### ISSUE TITLE
How do you test async requests using web::block?

### ISSUE THREAD

**Issue by Watercycle** [actix/actix-web#1139]
Running `cargo test` with
```rust
use futures::Future;
use failure::Error;
use actix_web::web;
use actix_web::error::BlockingError;

pub fn async_api_fn() -> impl Future<Item=String, Error=BlockingError<Error>> {
    web::block(|| {
        Ok("abc".to_string())
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use actix_web::dev::Service;
    use actix_web::{test, web, App};

    #[test]
    fn test_async_fn() {
        let mut app = test::init_service(
            App::new().route("/async_api_fn", web::get().to_async(async_api_fn))
        );
        let req = test::TestRequest::get().uri("/async_api_fn").to_request();
        let resp = test::block_on(app.call(req)).unwrap();

        assert!(resp.status().is_success());
    }
}
```
results in this 90% of the time (it does actually pass once awhile)
```
test tests::test_async_fn ... FAILED

failures:

---- tests::test_async_fn stdout ----
thread 'tests::test_async_fn' panicked at 'no Task is currently running', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/tas
k_impl/mod.rs:47:9
```
This is with `actix-web 1.0.8` on the `rust:1.37.0` Docker image. According to the docs, [block_on](https://docs.rs/actix-web/1.0.8/actix_web/test/fn.block_on.html) panics when used in a nested context - presumably that is the problem. This is a contrived example, but it's fairly common to call stuff like diesel/SQL in `web::block`.

**Comment by fafhrd91** [comment]
could you post backtrace

**Comment by Watercycle** [comment]
```
root@a49391895d9d:/app# RUST_BACKTRACE=full cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running target/debug/deps/main-59738d364cda0311

running 1 test
test tests::test_async_fn ... FAILED

failures:

---- tests::test_async_fn stdout ----
thread 'tests::test_async_fn' panicked at 'no Task is currently running', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/tas
k_impl/mod.rs:47:9
stack backtrace:
   0:     0x55b74dd1239b - backtrace::backtrace::libunwind::trace::hfe5db90796807973
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1:     0x55b74dd1239b - backtrace::backtrace::trace_unsynchronized::h34b865a835594335
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2:     0x55b74dd1239b - std::sys_common::backtrace::_print::h527254ae44989167
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x55b74dd1239b - std::sys_common::backtrace::print::he85dd5ddddf46503
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x55b74dd1239b - std::panicking::default_hook::{{closure}}::h847a2eb38b396f14
                               at src/libstd/panicking.rs:200
   5:     0x55b74dd1200a - std::panicking::default_hook::h2ca0f9a30a0e206b
                               at src/libstd/panicking.rs:211
   6:     0x55b74dd12b10 - std::panicking::rust_panic_with_hook::hffcefc09751839d1
                               at src/libstd/panicking.rs:477
   7:     0x55b74dd010b8 - std::panicking::begin_panic::haca656c33bd83e63
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:411
   8:     0x55b74dcffb18 - futures::task_impl::with::he73b01f3d7af2dfc
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:47
   9:     0x55b74dcffb62 - futures::task_impl::current::h9845692de8f535b2
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:118
  10:     0x55b74d89585e - futures::sync::oneshot::Inner<T>::recv::h205d7d8c2e665cd0
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/sync/oneshot.rs:261
  11:     0x55b74d897287 - <futures::sync::oneshot::Receiver<T> as futures::future::Future>::poll::h7565bf4db626af80
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/sync/oneshot.rs:448
  12:     0x55b74d876426 - <actix_threadpool::CpuFuture<I,E> as futures::future::Future>::poll::h25041f8e1df3ae48
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-threadpool-0.1.2/src/lib.rs:82
  13:     0x55b74d89288b - <futures::future::from_err::FromErr<A,E> as futures::future::Future>::poll::h19900ced11123f37
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/from_err.rs:29
  14:     0x55b74d86554b - <actix_web::handler::AsyncHandlerServiceResponse<T> as futures::future::Future>::poll::h87914de3773a9f92
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-1.0.8/src/handler.rs:249
  15:     0x55b74d866580 - <actix_web::handler::ExtractResponse<T,S> as futures::future::Future>::poll::h08a08dc5389be400
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-1.0.8/src/handler.rs:361
  16:     0x55b74d86696a - <actix_web::handler::ExtractResponse<T,S> as futures::future::Future>::poll::h08a08dc5389be400
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-1.0.8/src/handler.rs:370
  17:     0x55b74d89954d - <actix_web::route::RouteServiceWrapper<T> as actix_service::Service>::call::h1e3eb1449a2c7e4f
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-1.0.8/src/route.rs:364
  18:     0x55b74d90acc7 - <alloc::boxed::Box<S> as actix_service::Service>::call::h14043627dee61578
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-0.4.2/src/lib.rs:369
  19:     0x55b74d90e383 - <actix_web::route::RouteService as actix_service::Service>::call::h81d7b917d15ae010
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-1.0.8/src/route.rs:135
  20:     0x55b74d931500 - <actix_web::resource::ResourceService as actix_service::Service>::call::h9f5ab045bb329d28
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-1.0.8/src/resource.rs:568
  21:     0x55b74d92b5db - <actix_service::boxed::ServiceWrapper<T> as actix_service::Service>::call::hc56f87d8cea8231e
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-0.4.2/src/boxed.rs:144
  22:     0x55b74d90acc7 - <alloc::boxed::Box<S> as actix_service::Service>::call::h14043627dee61578
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-0.4.2/src/lib.rs:369
  23:     0x55b74d900f14 - <actix_web::app_service::AppRouting as actix_service::Service>::call::h59869b832f61b005
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-1.0.8/src/app_service.rs:411
  24:     0x55b74d8a4d17 - <actix_web::app_service::AppInitService<T,B> as actix_service::Service>::call::h9a5c002b8b0a521f
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-1.0.8/src/app_service.rs:255
  25:     0x55b74d89c2d5 - main::tests::test_async_fn::h93a2bf507cada294
                               at src/main.rs:73
  26:     0x55b74d89af2a - main::tests::test_async_fn::{{closure}}::h1fe05e4b17737040
                               at src/main.rs:68
  27:     0x55b74d86b03e - core::ops::function::FnOnce::call_once::hf31288e9d3328c8f
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:231
  28:     0x55b74d8b334f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h4a13ee3f0d7b4201
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  29:     0x55b74dd1544a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:82
  30:     0x55b74d8cd948 - std::panicking::try::h5a93466ab2078586
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:275
  31:     0x55b74d8cd948 - std::panic::catch_unwind::h752cbeae6ac7bdea
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:394
  32:     0x55b74d8cd948 - test::run_test::run_test_inner::{{closure}}::h206c9c16936edaca
                               at src/libtest/lib.rs:1466
  33:     0x55b74d8a87c5 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc7edbac42990d270
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/sys_common/backtrace.rs:77
  34:     0x55b74d8ac885 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::he53c58e7adee87af
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/mod.rs:470
  35:     0x55b74d8ac885 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h1aff7c42b6bb3726
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:315
  36:     0x55b74d8ac885 - std::panicking::try::do_call::h41f8559f88100f6c
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:296
  37:     0x55b74dd1544a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:82
  38:     0x55b74d8acf82 - std::panicking::try::hb54ba808181fe352
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:275
  39:     0x55b74d8acf82 - std::panic::catch_unwind::h555ccf4e835e93f4
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:394
  40:     0x55b74d8acf82 - std::thread::Builder::spawn_unchecked::{{closure}}::hd4dae6e19e80fc1a
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/thread/mod.rs:469
  41:     0x55b74d8acf82 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc35d54c07710e1a1
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:231
  42:     0x55b74dd06bef - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h42806b83647d4c79
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  43:     0x55b74dd14880 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h83c921c8e826dd1d
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  44:     0x55b74dd14880 - std::sys_common::thread::start_thread::h2613204ce513782e
                               at src/libstd/sys_common/thread.rs:13
  45:     0x55b74dd14880 - std::sys::unix::thread::Thread::new::thread_start::h4570080769500bcd
                               at src/libstd/sys/unix/thread.rs:79
  46:     0x7f76b8e52fa3 - start_thread
  47:     0x7f76b8d5c4cf - clone
  48:                0x0 - <unknown>


failures:
    tests::test_async_fn

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--bin main'

```

**Comment by fafhrd91** [comment]
use `let resp = test::block_fn(|| app.call(req)).unwrap();`
this happens because of some optimizations

**Comment by Watercycle** [comment]
That's straightforward. Thank you for looking into this!
