### ISSUE TITLE
CORS problems

### ISSUE THREAD

**Issue by pka** [actix/actix-web#117]
I've two problems with CORS headers.

When addding CORS middleware with
```
.resource("/projects/{id}", |r| {
                 cors::Cors::build().finish().unwrap().register(r);
```
actix-web is panicking in requests without ORIGIN header.
Request:
```
curl 'http://127.0.0.1:8000/projects/38'
```
Server:
```
thread 'arbiter:"656c57b6-8b14-421b-8a5f-15a7fabef926":"actor"' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:20
  11: <actix_web::middleware::cors::Cors as actix_web::middleware::Middleware<S>>::response
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.4.3/src/middleware/cors.rs:353
  12: <actix_web::route::RunMiddlewares<S>>::init
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.4.3/src/route.rs:343
  13: <actix_web::route::WaitingResponse<S>>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.4.3/src/route.rs:321
  14: <actix_web::route::ComposeState<S>>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.4.3/src/route.rs:176
  15: <actix_web::route::Compose<S> as futures::future::Future>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.4.3/src/route.rs:205
  16: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/future/mod.rs:113
  17: <actix_web::pipeline::WaitingResponse<S, H>>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.4.3/src/pipeline.rs:315
  18: <actix_web::pipeline::PipelineState<S, H>>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.4.3/src/pipeline.rs:53
  19: <actix_web::pipeline::Pipeline<S, H> as actix_web::server::HttpHandlerTask>::poll_io
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.4.3/src/pipeline.rs:181
  20: <actix_web::server::h1::Http1<T, H>>::poll_io
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.4.3/src/server/h1.rs:211
  21: <actix_web::server::h1::Http1<T, H>>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.4.3/src/server/h1.rs:105
  22: <actix_web::server::channel::HttpChannel<T, H> as futures::future::Future>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-0.4.3/src/server/channel.rs:87
  23: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/future/mod.rs:113
  24: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/mod.rs:289
  25: <futures::task_impl::Spawn<T>>::enter::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/mod.rs:363
  26: futures::task_impl::std::set
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/std/mod.rs:78
  27: <futures::task_impl::Spawn<T>>::enter
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/mod.rs:363
  28: <futures::task_impl::Spawn<T>>::poll_future_notify
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/mod.rs:289
  29: tokio_core::reactor::Core::dispatch_task::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:359
  30: <scoped_tls::ScopedKey<T>>::set
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.1/src/lib.rs:155
  31: tokio_core::reactor::Core::dispatch_task
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:358
  32: tokio_core::reactor::Core::dispatch
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:319
  33: tokio_core::reactor::Core::poll
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:307
  34: tokio_core::reactor::Core::run
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:241
  35: actix::arbiter::Arbiter::new::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.5.1/src/arbiter.rs:89
```

A workaround is adding send_wildcard:
```
cors::Cors::build().send_wildcard().finish().unwrap().register(r)
```

And since 0.4.3 (resp. >0.4.0) I get a 400 Bad Request for PATCH requests:

* OPTIONS Request: OK
```
curl -v 'http://127.0.0.1:8000/projects/38' -X OPTIONS -H 'Access-Control-Request-Method: PATCH' -H 'Access-Control-Request-Headers: content-type' -H 'Origin: http://localhost:5000'
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> OPTIONS /projects/38 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:8000
> Accept: */*
> Access-Control-Request-Method: PATCH
> Access-Control-Request-Headers: content-type
> Origin: http://localhost:5000
> 
< HTTP/1.1 200 OK
< content-length: 0
< access-control-allow-headers: content-type
< access-control-allow-origin: *
< access-control-allow-methods: PATCH,HEAD,POST,GET,DELETE,PUT,OPTIONS
< vary: Origin
< date: Sat, 10 Mar 2018 14:44:58 GMT
```
* PATCH Request: 400 Bad Request
```
curl -v 'http://127.0.0.1:8000/projects/38' --data-binary @data.json -X PATCH -H 'Content-Type: application/vnd.api+json' -H 'Origin: http://localhost:5000'
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> PATCH /projects/38 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:8000
> Accept: */*
> Content-Type: application/vnd.api+json
> Origin: http://localhost:5000
> Content-Length: 105
> 
* upload completely sent off: 105 out of 105 bytes
< HTTP/1.1 400 Bad Request
< content-length: 0
< date: Sat, 10 Mar 2018 14:44:27 GMT
< 
```

Same request responds as expected with actix-web 5634e5794f:
```
curl -v 'http://127.0.0.1:8000/projects/38' --data-binary @data.json -X PATCH -H 'Accept: application/vnd.api+json' -H 'Content-Type: application/vnd.api+json' -H 'Origin: http://localhost:5000'
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> PATCH /projects/38 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:8000
> Accept: application/vnd.api+json
> Content-Type: application/vnd.api+json
> Origin: http://localhost:5000
> Content-Length: 105
> 
* upload completely sent off: 105 out of 105 bytes
< HTTP/1.1 200 OK
< content-length: 11
< content-type: application/vnd.api+json
< access-control-allow-origin: *
< vary: Origin
< date: Sat, 10 Mar 2018 14:55:05 GMT
```

**Comment by fafhrd91** [comment]
Thanks for report! I will fix this shortly

**Comment by fafhrd91** [comment]
panic is fixed in master. but i can not reproduce second problem.
could you enable logger

```rust
::std::env::set_var("RUST_LOG", "actix_web=info");
env_logger::init();
```

**Comment by pka** [comment]
Log output:
```
 WARN 2018-03-10T17:52:11Z: actix_web::pipeline: Error occured during request handling: Content type error
 INFO 2018-03-10T17:52:11Z: actix_web::middleware::logger: 127.0.0.1:48604 [10/Mar/2018:18:52:11 +0100] "PATCH /projects/38 HTTP/1.1" 400 0 "-" "curl/7.35.0" 0.000519
```

**Comment by fafhrd91** [comment]
this is different problem. let me check

**Comment by fafhrd91** [comment]
second bug is fixed in master too. i will make new release later today

**Comment by pka** [comment]
Tested with 0.4.6 and everything is working now. Thanks for your work on this exciting piece of software!
