### ISSUE TITLE
thread 'actix-server accept loop' panicked at 'Poll error: Interrupted system call (os error 4)', [...]/actix-server-2.0.0-beta.2/src/accept.rs:164:37

### ISSUE THREAD

**Issue by Yoric** [actix/actix-web#1942]
Your issue may already be reported!
Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

I don't know if this bug can affect web servers in production but I encounter it daily as a developer.

## Steps to reproduce

1. Build and launch an actix server (tested with Ubuntu 20.10).
2. Suspend the computer.
3. Resume the computer.

```log
thread 'actix-server accept loop' panicked at 'Poll error: Interrupted system call (os error 4)', /home/yoric/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.2/src/accept.rs:164:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
   2: actix_server::accept::Accept::poll_with::{{closure}}
             at /home/yoric/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.2/src/accept.rs:164
   3: core::result::Result<T,E>::unwrap_or_else
             at /home/yoric/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:825
   4: actix_server::accept::Accept::poll_with
             at /home/yoric/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.2/src/accept.rs:162
   5: actix_server::accept::Accept::start::{{closure}}
             at /home/yoric/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.2/src/accept.rs:114
```

While the situation in which a server goes to sleep is unusual, I can think of applications that embed a web server for use on a desktop/laptop, which makes it a potential issue for some apps.

## Expected Behavior

The web server should be able to somehow resume activity when the computer wakes up.

## Your Environment

* Rust Version (I.e, output of `rustc -V`):1.48
* Actix Web Version: 2.0.0-beta.2

**Comment by fakeshadow** [comment]
```rust
            if let Err(e) = self.poll.poll(&mut events, None) {
                if e.kind() == std::io::ErrorKind::Interrupted {
                    continue;
                } else {
                    panic!("Poll error: {}", e);
                }
            }
```

I personally think interrupted should not be handled. mio remove the auto retry for a reason. so I would leave the change to others.

**Comment by shuoli84** [comment]
Met same problem when strace attach to an running server, it failed with
```
[pid  8114] epoll_wait(104,  <unfinished ...>
[pid  8123] write(2, "' panicked at '", 15) = 15
[pid  8113] epoll_wait(109,  <unfinished ...>
[pid  8123] write(2, "Poll error: Interrupted system call (os error 4)", 48 <unfinished ...>
[pid  8112] epoll_wait(67,  <unfinished ...>
[pid  8123] <... write resumed> )       = 48
[pid  8110] epoll_wait(113,  <unfinished ...>
[pid  8123] write(2, "', ", 3)          = 3
[pid  8109] epoll_wait(117,  <unfinished ...>
[pid  8123] write(2, "/opt/tiger/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.2/src/accept.rs", 98 <unfinished ...>
```

**Comment by shuoli84** [comment]
FYI: Seems golang automatically retries net related syscalls.
```
Packages <code>os</code> and <code>net</code> now automatically
      retry system calls that fail with <code>EINTR</code>. Previously
      this led to spurious failures, which became more common in Go
      1.14 with the addition of asynchronous preemption. Now this is
      handled transparently.
```
