### ISSUE TITLE
index out of bounds: the len is 3 but the index is 3 / "Thread pool is gone"

### ISSUE THREAD

**Issue by Ploppz** [actix/actix-web#2026]
I have a web API which also runs a poller that does something every 5 seconds, started with `actix_rt::spawn(async move { phaedra_poller.run().await });`.
While developing this poller module, it turns out it makes actix panic inside a `actix_web::block`.
It still happens when I replace the aforementioned line with just `phaedra_poller.run().await;`. So no HttpServer will ever be created, it just runs that future which loops forever.
Here is reduced code, followed by panic backlog. And also the backtrace of the error log message (it panics, and then the code returns an error).

```rust
pub struct PhaedraPoller {
    state: Arc<State>,
}

impl PhaedraPoller {
    pub fn new(state: Arc<State>) -> Self {
        Self { state }
    }
    pub async fn run(&mut self) {
        let mut i = 0;
        loop {
            let log = self.state.log.new(o!("phaedra poller" => i));
            i += 1;

            let seconds = self.state.config.load().phaedra.poll_interval_s;
            tokio::time::delay_for(Duration::from_millis((seconds * 1000.0) as u64)).await;

            match self.poll(log).await {
                Ok(()) => (),
                Err(e) => error!(self.state.log, #"phaedra-poller", ""; "error" => ?e),
            }
        }
    }
    pub async fn poll(&mut self, log: Logger) -> Result<()> {
        use diesel::sql_types::*;
        let config = self.state.config.load();

        let conn = self.state.get_conn().await?;
        let barcodes: Vec<String> =
            block(move || p::plate.select(p::barcode).load::<String>(&conn)).await?;

        info!(log, #"phaedra-poller", "Poll phaedra"; "n barcodes" => barcodes.len());
        // Break requests into max 20 barcodes each, to not create a too big request
        let mut phaedra_plates = vec![];
        for barcodes in barcodes.chunks(50) {
            // [REDUCED]
            // Sends requests fetching some strings that are pushed to `phaedra_plates`
        }

        info!(log, #"phaedra-poller", "Polled phaedra"; "n plates returned" => phaedra_plates.len());
        let conn = self.state.get_conn().await?;
        block(move || {
            for plate in phaedra_plates {
                // Parse the source path from phaedra, to determine the measurement timestamp
                let relative_path = plate.properties.0.minos_source_url.path();
                let phaedra_meas_timestamp =
                    MeasurementInfo::from_relative_path(Path::new(relative_path)) // PANIC
                        .with_context(|| format!("Failed to decompose {} into a MeasurementInfo", relative_path))?
                        .path_meas_timestamp;
                warn!(log, "DBG"; "flags" => ?plate.flags, "meas timestamp" => ?phaedra_meas_timestamp);

                let measurement_id = m::measurement
                    // (reduced query)
                    .select(m::id)
                    .first::<i64>(&conn)
                    .context("Could not find measurement with timestamp to update flags")?;
                let n_updated = diesel::update(m::measurement)
                    // (reduced query)
                    .execute(&conn)?;
                anyhow::ensure!(n_updated == 1, "No measurements updated with flags");
            }
            Ok::<(), anyhow::Error>(())
        })
        .await?;
        Ok(())
    }
}

```

```
thread 'actix-web' panicked at 'index out of bounds: the len is 3 but the index is 3', /home/ploppz/.cargo/git/checkouts/common-rs-e100cf7443f6f326/057b535/src/model/measurement.rs:255:21
stack backtrace:
   0:     0x5585f0a9b9b7 - std::backtrace_rs::backtrace::libunwind::trace::h746c3e9529d524bc
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5585f0a9b9b7 - std::backtrace_rs::backtrace::trace_unsynchronized::h86340908ff889faa
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5585f0a9b9b7 - std::sys_common::backtrace::_print_fmt::h43f85f9b18230404
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5585f0a9b9b7 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc132ae1a5b5aa7cd
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5585f0ac4c2c - core::fmt::write::hdf023a0036d2a25f
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/core/src/fmt/mod.rs:1078:17
   5:     0x5585f0a93862 - std::io::Write::write_fmt::h8580846154bcb66a
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/io/mod.rs:1519:15
   6:     0x5585f0a9dbb5 - std::sys_common::backtrace::_print::h7ee55fed88d107a3
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5585f0a9dbb5 - std::sys_common::backtrace::print::h54a7d3e52a524177
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5585f0a9dbb5 - std::panicking::default_hook::{{closure}}::h60921e857bf55a40
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/panicking.rs:208:50
   9:     0x5585f0a9d70a - std::panicking::default_hook::hf0f9afb1017317fc
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/panicking.rs:225:9
  10:     0x5585f0a9e351 - std::panicking::rust_panic_with_hook::h8d66bf42b407aaea
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/panicking.rs:591:17
  11:     0x5585f0a9de97 - std::panicking::begin_panic_handler::{{closure}}::hde71edcd925d0c5e
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/panicking.rs:497:13
  12:     0x5585f0a9be7c - std::sys_common::backtrace::__rust_end_short_backtrace::h8a3c7d6cea578919
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5585f0a9ddf9 - rust_begin_unwind
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/panicking.rs:493:5
  14:     0x5585f0ac2161 - core::panicking::panic_fmt::h20225113c4a2f8fd
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/core/src/panicking.rs:92:14
  15:     0x5585f0ac2122 - core::panicking::panic_bounds_check::h5752306d250b5620
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/core/src/panicking.rs:69:5
  16:     0x5585efdd4f42 - <usize as core::slice::index::SliceIndex<[T]>>::index::h65b31bdb052337c8
                               at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:182:10
  17:     0x5585efdcd6d3 - core::slice::index::<impl core::ops::index::Index<I> for [T]>::index::h486a0d280866c23b
                               at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:15:9
  18:     0x5585efddb949 - <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index::h2ce37467d016734a
                               at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2161:9
  19:     0x5585efde0125 - common::model::measurement::MeasurementInfo::from_relative_path::h62732bc6a8e8547c
                               at /home/ploppz/.cargo/git/checkouts/common-rs-e100cf7443f6f326/057b535/src/model/measurement.rs:255:21
  20:     0x5585ef20aa12 - api::phaedra_poller::PhaedraPoller::poll::{{closure}}::{{closure}}::h5ea63a500811b3de
                               at /home/ploppz/oa/hci/api-rs/src/phaedra_poller.rs:103:21
  21:     0x5585ef5591ae - actix_threadpool::run::{{closure}}::{{closure}}::h4a90d9dc08ae8ed9
                               at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-threadpool-0.3.2/src/lib.rs:65:33
  22:     0x5585ef55f08a - <F as threadpool::FnBox>::call_box::h4d9c3e7a22ced3a9
                               at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.8.1/src/lib.rs:95:9
  23:     0x5585f07cc1bf - threadpool::spawn_in_pool::{{closure}}::h028aa39af3a8c5bd
                               at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/threadpool-1.8.1/src/lib.rs:769:17
  24:     0x5585f07c304e - std::sys_common::backtrace::__rust_begin_short_backtrace::hbffb1b057238b70c
                               at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  25:     0x5585f07c6f5b - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::ha74d3229ededcdc8
                               at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:474:17
  26:     0x5585f07cdc6f - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h777d569bf973ddaa
                               at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:322:9
  27:     0x5585f07ce90c - std::panicking::try::do_call::h454607b288be4bf8
                               at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  28:     0x5585f07cf13d - __rust_try
  29:     0x5585f07ce877 - std::panicking::try::h51ca5d6e81450561
                               at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  30:     0x5585f07ce65f - std::panic::catch_unwind::h54660458ffaf43cc
                               at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:396:14
  31:     0x5585f07c6d8c - std::thread::Builder::spawn_unchecked::{{closure}}::h3df1c902a107e312
                               at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:473:30
  32:     0x5585f07d283f - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha759b51fbfdfd393
                               at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  33:     0x5585f0aa56fa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hea1090dbdcecbf5a
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/alloc/src/boxed.rs:1328:9
  34:     0x5585f0aa56fa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8d5723d3912bd325
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/alloc/src/boxed.rs:1328:9
  35:     0x5585f0aa56fa - std::sys::unix::thread::Thread::new::thread_start::hc17a425ca2995724
                               at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/sys/unix/thread.rs:71:17
  36:     0x7fbc3cc643e9 - start_thread
  37:     0x7fbc3ca4c293 - __GI___clone
  38:                0x0 - <unknown>
Feb 25 16:40:42.702 ERRO error: Thread pool is gone

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.34/src/error.rs:464:25
   1: api::phaedra_poller::PhaedraPoller::poll::{{closure}}
             at ./src/phaedra_poller.rs:137:15
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   3: api::phaedra_poller::PhaedraPoller::run::{{closure}}
             at ./src/phaedra_poller.rs:36:19
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   5: api::main::{{closure}}
             at ./src/main.rs:140:5
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   7: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::{{closure}}
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:526:65
   8: tokio::coop::with_budget::{{closure}}
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:127:9
   9: std::thread::local::LocalKey<T>::try_with
             at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  10: std::thread::local::LocalKey<T>::with
             at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  11: tokio::coop::with_budget
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:120:5
      tokio::coop::budget
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:96:5
      <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:526:42
  12: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/macros/scoped_tls.rs:63:9
  13: tokio::task::local::LocalSet::with
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:440:9
  14: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:516:9
  15: tokio::task::local::LocalSet::run_until::{{closure}}
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:390:9
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  17: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/basic_scheduler.rs:131:58
  18: tokio::coop::with_budget::{{closure}}
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:127:9
  19: std::thread::local::LocalKey<T>::try_with
             at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  20: std::thread::local::LocalKey<T>::with
             at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  21: tokio::coop::with_budget
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:120:5
      tokio::coop::budget
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:96:5
      tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/basic_scheduler.rs:131:35
  22: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/basic_scheduler.rs:213:29
  23: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/macros/scoped_tls.rs:63:9
  24: tokio::runtime::basic_scheduler::enter
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/basic_scheduler.rs:213:5
  25: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/basic_scheduler.rs:123:9
  26: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/mod.rs:444:34
  27: tokio::runtime::context::enter
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/context.rs:72:5
  28: tokio::runtime::handle::Handle::enter
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/handle.rs:76:9
  29: tokio::runtime::Runtime::block_on
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/mod.rs:441:9
  30: tokio::task::local::LocalSet::block_on
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:351:9
  31: actix_rt::runtime::Runtime::block_on
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/runtime.rs:89:9
  32: actix_rt::builder::SystemRunner::block_on
             at /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/builder.rs:187:19
  33: api::main
             at ./src/main.rs:54:1
  34: core::ops::function::FnOnce::call_once
             at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  35: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  36: std::rt::lang_start::{{closure}}
             at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  37: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/panic.rs:396:14
      std::rt::lang_start_internal
             at /rustc/2225ee1b62ff089917434aefd9b2bf509cfa087f/library/std/src/rt.rs:51:25
  38: std::rt::lang_start
             at /home/ploppz/.rustup/toolchains/nightly-2020-12-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  39: main
  40: __libc_start_main
  41: _start
```

The panic backtrace points to the line marked with `// PANIC` in the code, which I think is rather arbitrary because that code is nothing special:
```rust
    pub fn from_relative_path(path: &Path) -> Option<Self> {
        let path = path.strip_prefix("/").unwrap_or(path);
        let components = path.iter().collect::<Vec<_>>();
        let project = components[0].to_str()?.to_owned();
        let experiment = components[1].to_str()?.to_owned();
        let plate = components[3].to_str()?.to_owned(); // <--- panics here
        // ....
```

**Comment by fakeshadow** [comment]
How is this related to actix-web? Your code makes panic inside `web::block` and actix-web just catch the panic and return error.

**Comment by robjtede** [comment]
The error message is from here:
https://docs.rs/actix-threadpool/0.3.3/src/actix_threadpool/lib.rs.html#47

Your code panics inside the worker thread (prints backtrace) and `.await?;` returns the error.

Will close but feel free to ask more Qs if it's not clear what's happening.

**Comment by Ploppz** [comment]
Oh, sorry. It did not appear to me that my code panics inside web::block. The errors were rather mystical to me.
And still I don't really understand, because I don't have any unwraps or panics in my code, and the backtrace does not point to anything notable in my code. And there is no panic backtrace other than the `index out of bounds: the len is 3 but the index is 3` which comes from actix_web. So if it panics it does so silently. So while it's not related to to actix-web, does anyone have any ideas what happens to the original backtrace or how to get an idea where it panics?

**Comment by fakeshadow** [comment]
Like error showed. You are accessing your `components` on index 3 while the length is 3 so you get a index out of bound panic.
Try use something like `components.get(3)` to get your bound checked if you are not sure how long it is.

**Comment by Ploppz** [comment]
Oh, it's so obvious but I've been staring myself blind at this code.
Thanks!

**Comment by robjtede** [comment]
The threads set up by the threadpool just happen to be called "actix-web" which probably threw you off.
