### ISSUE TITLE
actix-multipart-0.3.0 `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by hardcore-sushi** [actix/actix-web#2202]
## Expected Behavior
Field::next().await should not panic when uploading many files quickly.

## Current Behavior
Field::next().await causes:
```
thread 'actix-rt:worker:4' panicked at 'called `Option::unwrap()` on a `None` value', /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-multipart-0.3.0/src/server.rs:427:40
```

## Steps to Reproduce
Here is a simplified version of my code:
```
const FILE_CHUNK_SIZE: usize = 1023996;

async fn handle_send_file(req: HttpRequest, mut payload: Multipart) -> HttpResponse {
    while let Ok(Some(mut field)) = payload.try_next().await {
        let content_disposition = field.content_disposition().unwrap();
        let mut pending_buffer = Vec::new();
        let mut chunk_buffer = Vec::with_capacity(FILE_CHUNK_SIZE);
        loop {
            chunk_buffer.extend(&pending_buffer);
            pending_buffer.clear();
            println!("Before a potential crash");
            while let Some(Ok(chunk)) = field.next().await { // <== the crash seems to happen here
                println!("When I see the panic error message, this line is not printed");
                if chunk_buffer.len()+chunk.len() <= FILE_CHUNK_SIZE {
                    chunk_buffer.extend(chunk);
                } else if chunk_buffer.len() == FILE_CHUNK_SIZE {
                    pending_buffer.extend(chunk);
                    break;
                } else {
                    let remaining = FILE_CHUNK_SIZE - chunk_buffer.len();
                    chunk_buffer.extend(&chunk[..remaining]);
                    pending_buffer.extend(&chunk[remaining..]);
                    break;
                }
            }

            //sending chunk_buffer through tokio::net::TcpStream and wait for a response with tokio::net::TcpStream::read().await...

            if chunk_buffer.len() < FILE_CHUNK_SIZE {
                break;
            } else {
                chunk_buffer.clear();
            }
        }
    }
    HttpResponse::Ok().finish()
}
```
Here is the logs I get with `RUST_BACKTRACE=full`:
```
thread 'actix-rt:worker:7' panicked at 'called `Option::unwrap()` on a `None` value', /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-multipart-0.3.0/src/server.rs:427:40
stack backtrace:
   0:     0x564ad5280cd0 - std::backtrace_rs::backtrace::libunwind::trace::h5e9d00f0cdf4f57e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x564ad5280cd0 - std::backtrace_rs::backtrace::trace_unsynchronized::hd5302bd66215dab9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x564ad5280cd0 - std::sys_common::backtrace::_print_fmt::ha0237cd11a34e2bf
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x564ad5280cd0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h171d4c10df1a98ee
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x564ad529fa7c - core::fmt::write::h89e4288724daa3fa
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
   5:     0x564ad5279632 - std::io::Write::write_fmt::h6d40f996e84584d9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
   6:     0x564ad5282f15 - std::sys_common::backtrace::_print::h0c0b93221682afc8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x564ad5282f15 - std::sys_common::backtrace::print::h57a9f95204c2fdd6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x564ad5282f15 - std::panicking::default_hook::{{closure}}::h4245258b50e37e69
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
   9:     0x564ad5282a73 - std::panicking::default_hook::h7b00dcc1d0944747
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:225:9
  10:     0x564ad52836b1 - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:591:17
  11:     0x564ad52831c7 - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:495:13
  12:     0x564ad528116c - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x564ad5283159 - rust_begin_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
  14:     0x564ad529e5d1 - core::panicking::panic_fmt::hcd56f7f635f62c74
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
  15:     0x564ad529e51d - core::panicking::panic::h07405d6be4bce887
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:50:5
  16:     0x564ad47bf88c - core::option::Option<T>::unwrap::h39d1d1c75ae0723f
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:386:21
  17:     0x564ad47b8c69 - <actix_multipart::server::Field as futures_core::stream::Stream>::poll_next::he21e2a8708f3118c
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-multipart-0.3.0/src/server.rs:427:17
  18:     0x564ad47395ac - futures_util::stream::stream::StreamExt::poll_next_unpin::h616f5fd2e6bc8823
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/stream/stream/mod.rs:1407:9
  19:     0x564ad472e309 - <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll::he0248161f58638c5
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/stream/stream/next.rs:35:9
  20:     0x564ad466fdaa - aira::handle_send_file::{{closure}}::hfe084ad18a2c23ae
                               at /home/hardcoresushi/AIRA/src/main.rs:373:49
  21:     0x564ad467fa92 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h43079635e3b913e9
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  22:     0x564ad4629646 - <actix_web::handler::HandlerServiceResponse<T,R> as core::future::future::Future>::poll::hbafa76ca5ec73726
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/handler.rs:138:15
  23:     0x564ad462e5dd - <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll::h87ca362c23f3fb8c
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/handler.rs:247:20
  24:     0x564ad478646a - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::ha2ac3a5baead7c7c
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/future/future/map.rs:55:37
  25:     0x564ad46481e1 - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h17d994e68a785ead
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/lib.rs:102:13
  26:     0x564ad47f9f42 - <core::pin::Pin<P> as core::future::future::Future>::poll::h86832158e690a4a1
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  27:     0x564ad47f9f42 - <core::pin::Pin<P> as core::future::future::Future>::poll::h86832158e690a4a1
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  28:     0x564ad47e612e - <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::ha3120bbb69f46ca1
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/future/either.rs:73:33
  29:     0x564ad47f9f42 - <core::pin::Pin<P> as core::future::future::Future>::poll::h86832158e690a4a1
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  30:     0x564ad468ea73 - actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response::h6abd17f9153489a0
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.2.0/src/h1/dispatcher.rs:400:54
  31:     0x564ad4693d9c - <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll::h62ec4c5557678a03
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.2.0/src/h1/dispatcher.rs:783:38
  32:     0x564ad46bf7b1 - actix_http::service::State<T,S,B,X,U>::poll::h74db706dd15f6d7f
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.2.0/src/service.rs:682:36
  33:     0x564ad46c1a31 - <actix_http::service::HttpServiceHandlerResponse<T,S,B,X,U> as core::future::future::Future>::poll::h9b0d9b4dbca6a279
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.2.0/src/service.rs:661:9
  34:     0x564ad4654b6b - <actix_service::and_then::AndThenServiceResponse<A,B> as core::future::future::Future>::poll::h0303c6f1cb128c51
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-1.0.6/src/and_then.rs:101:34
  35:     0x564ad472f0fe - <actix_server::service::StreamService<T> as actix_service::Service>::call::{{closure}}::h648f27d65dcd62a4
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.4/src/service.rs:85:33
  36:     0x564ad467ebc9 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h07cef1a4c22f1e25
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  37:     0x564ad467bd14 - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h5c67880e064c205f
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/core.rs:173:17
  38:     0x564ad46a1747 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hee5307bdf16b1076
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/loom/std/unsafe_cell.rs:14:9
  39:     0x564ad467bad3 - tokio::runtime::task::core::Core<T,S>::poll::h52af5f8015227116
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/core.rs:158:13
  40:     0x564ad46cc1ab - tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}::h0a94d516fd8c9c09
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/harness.rs:107:27
  41:     0x564ad46de160 - core::ops::function::FnOnce::call_once::h9cc196c29216e665
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  42:     0x564ad46b767a - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h2c9192120f2f8a66
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  43:     0x564ad474d36d - std::panicking::try::do_call::hba59ffcc6c90a2bb
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  44:     0x564ad474e05d - __rust_try
  45:     0x564ad474c6c5 - std::panicking::try::hb52cf2318be66a8e
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  46:     0x564ad46b79ca - std::panic::catch_unwind::h4ad95d0cd6acb598
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  47:     0x564ad46cb904 - tokio::runtime::task::harness::Harness<T,S>::poll::h6d741d5d9cf0dbce
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/harness.rs:89:19
  48:     0x564ad46468a0 - tokio::runtime::task::raw::poll::hf0e918b34a3345c3
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/raw.rs:104:5
  49:     0x564ad4dcecdf - tokio::runtime::task::raw::RawTask::poll::h91456a7c8e63375e
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/raw.rs:66:18
  50:     0x564ad4de95c1 - tokio::runtime::task::Notified<S>::run::h98b7600f40f89811
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/mod.rs:169:9
  51:     0x564ad4dde50b - tokio::task::local::LocalSet::tick::{{closure}}::hc3d569347f6dd0b0
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/task/local.rs:408:54
  52:     0x564ad4d9c1e9 - tokio::coop::with_budget::{{closure}}::h041cfba7d67fd7b4
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:127:9
  53:     0x564ad4dcd229 - std::thread::local::LocalKey<T>::try_with::ha6788985cd2b7c75
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  54:     0x564ad4dcc2ca - std::thread::local::LocalKey<T>::with::h1db7004e49a1b5f6
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  55:     0x564ad4dde49f - tokio::coop::with_budget::h4f776609681aadc9
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:120:5
  56:     0x564ad4dde49f - tokio::coop::budget::h4bebc89461b39366
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:96:5
  57:     0x564ad4dde49f - tokio::task::local::LocalSet::tick::h7cf19f6e26434343
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/task/local.rs:408:31
  58:     0x564ad4c751c1 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::h130ed9ab75e5b6ff
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/task/local.rs:532:16
  59:     0x564ad4c7b862 - tokio::macros::scoped_tls::ScopedKey<T>::set::h69487495dd567fc4
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/macros/scoped_tls.rs:63:9
  60:     0x564ad4c74792 - tokio::task::local::LocalSet::with::ha7042f3675487e4c
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/task/local.rs:442:9
  61:     0x564ad4c74fb4 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::hed4b5abcbddbf32e
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/task/local.rs:518:9
  62:     0x564ad4c74bf9 - tokio::task::local::LocalSet::run_until::{{closure}}::hf57b194cd973b298
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/task/local.rs:392:9
  63:     0x564ad4c6da10 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h05a59ffb4194370f
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  64:     0x564ad4c91fc5 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}::h3d52bc35e95dec7a
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/basic_scheduler.rs:131:58
  65:     0x564ad4c655ab - tokio::coop::with_budget::{{closure}}::h3c7cff427653fb9a
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:127:9
  66:     0x564ad4c95e99 - std::thread::local::LocalKey<T>::try_with::h94d57184f6c2dcee
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  67:     0x564ad4c9395e - std::thread::local::LocalKey<T>::with::h1c6b11a6c8203550
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  68:     0x564ad4c918ce - tokio::coop::with_budget::ha78f097edb92431b
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:120:5
  69:     0x564ad4c918ce - tokio::coop::budget::h3702159d566c42f2
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:96:5
  70:     0x564ad4c918ce - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::haa7ca0b8a05ea24c
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/basic_scheduler.rs:131:35
  71:     0x564ad4c9292e - tokio::runtime::basic_scheduler::enter::{{closure}}::h161876f7274ed9d2
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/basic_scheduler.rs:213:29
  72:     0x564ad4c7baa3 - tokio::macros::scoped_tls::ScopedKey<T>::set::hf359fa18d15fe74d
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/macros/scoped_tls.rs:63:9
  73:     0x564ad4c927db - tokio::runtime::basic_scheduler::enter::h6f4749d429ec59f3
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/basic_scheduler.rs:213:5
  74:     0x564ad4c90df8 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::h94a17d8b84c448ab
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/basic_scheduler.rs:123:9
  75:     0x564ad4c92ad7 - tokio::runtime::Runtime::block_on::{{closure}}::h43bc30514df10944
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/mod.rs:444:34
  76:     0x564ad4c8dc34 - tokio::runtime::context::enter::h57210e54d3adf5cf
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/context.rs:72:5
  77:     0x564ad4c8dabe - tokio::runtime::handle::Handle::enter::h832b63c04842d770
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/handle.rs:76:9
  78:     0x564ad4c92a68 - tokio::runtime::Runtime::block_on::h8d3b78f7ac292d29
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/mod.rs:441:9
  79:     0x564ad4c748b3 - tokio::task::local::LocalSet::block_on::hff183f0acd9fe3d3
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/task/local.rs:353:9
  80:     0x564ad4c75c48 - actix_rt::runtime::Runtime::block_on::he29ae0be8379a37d
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/runtime.rs:89:9
  81:     0x564ad4c6ead9 - actix_rt::arbiter::Arbiter::new::{{closure}}::hdb563d94ea847fa5
                               at /home/hardcoresushi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/arbiter.rs:137:31
  82:     0x564ad4c5eab5 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfd3aab8ee18c47b3
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  83:     0x564ad4c90521 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hcf47f732ecdcb71f
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:474:17
  84:     0x564ad4c82101 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h4360a4e364022ba1
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  85:     0x564ad4c5fa42 - std::panicking::try::do_call::h6f5c05d2de8f74a0
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  86:     0x564ad4c61efd - __rust_try
  87:     0x564ad4c5f6b4 - std::panicking::try::hfa13b94c05a2e1d3
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  88:     0x564ad4c823e3 - std::panic::catch_unwind::hd6417a1d3f8a3917
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  89:     0x564ad4c90310 - std::thread::Builder::spawn_unchecked::{{closure}}::h7ba4786625406cb9
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:473:30
  90:     0x564ad4c84adf - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1b464b25226681ca
                               at /home/hardcoresushi/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  91:     0x564ad528aeda - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h61144a2be4ee36d8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
  92:     0x564ad528aeda - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcf5d395fdd120c17
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
  93:     0x564ad528aeda - std::sys::unix::thread::Thread::new::thread_start::hb5e40d3d934ebb7a
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  94:     0x7f7cfb19aea7 - start_thread
  95:     0x7f7cfaf80def - clone
  96:                0x0 - <unknown>
```

## Context
I'm writing a desktop software with a rust daemon as backend and a web frontend that runs in the browser. They communicate via HTTP requests and Websocket (on localhost). I implemented a feature that allows the frontend to upload files to the backend  using multipart with actix-web . However sometime this bug happens when I quickly upload many files.

## Your Environment
* Rust Version: rustc 1.51.0 (2fd73fabe 2021-03-23)
* Actix Web Version: 3.3.2
* Actix Multipart Version: 0.3.0
* OS: Linux 5.10.0-6-amd64 Debian 5.10.28-1 (2021-04-09) x86_64 GNU/Linux

**Comment by aliemjay** [comment]
This is because your code may call `field.next()` again after a previous call that returned `None` (i.e. the stream has been exhausted). A panic in this case is expected (see the docs https://docs.rs/futures/0.3.15/futures/stream/trait.Stream.html#tymethod.poll_next).  A minimal code to reproduce
```rust
while let Some(_) = field.next().await {}
field.next().await // << This will definitely panic!
```

BTW, If I understand your code correctly, then all you need is to wrap `tcp_stream` in `tokio::BufStream` and then the code would be as simple as :
```rust
let buf_stream = tokio::BufStream::with_capacity(CHUNK_SIZE, CUNK_SIZE, tcp_stream);
let mut buf_stream = field.try_fold(buf_stream, |mut buf, chunk| async { 
    buf.write(chunk).await?;
    Ok(buf)
})?;
buf_stream.flush().await?;
```

**Comment by hardcore-sushi** [comment]
Well... I can't reproduce this bug 😅. But I think you're right, under certain circumstances, my code could call `field.next()` after it returned `None`.
However, I don't think the code you suggested would fit my need. As I understand, it writes the buffer once the whole field is received, whatever its length. My program requires the field to be sent in chunks of the same length to the remote `TcpStream`, and waits for an acknowledgment before sending the next chunk.

**Comment by aliemjay** [comment]
> Well... I can't reproduce this bug sweat_smile. But I think you're right, under certain circumstances, my code could call `field.next()` after it returned `None`.

Well, looking at the backtrace, this is the only the only reason it panics.



> As I understand, it writes the buffer once the whole field is received, whatever its length.

No, this will send every recieved chunk of the field individually, and `BufStream` will guarantee that it will send at least `CHUNK_SIZE` chunks to the underlying tcp stream.


> My program requires the field to be sent in chunks of the same length to the remote `TcpStream`, and waits for an acknowledgment before sending the next chunk.

Oh, handling this manually makes sense now.

**Comment by aliemjay** [comment]
> This is because your code may call `field.next()` again after a previous call that returned `None` (i.e. the stream has been exhausted).

@robjtede Is this bhevior ok here? Should we fix it?

**Comment by hardcore-sushi** [comment]
Oh OK. I'm new to rust and asynchronous programming, thanks for your help !
