### ISSUE TITLE
actix-web with aws-sdk-rust thread panics

### ISSUE THREAD

**Issue by doums** [actix/actix-web#2297]
Hi,

I'm working on an API built with actix-web and I try to use [aws-sdk-rust](https://github.com/awslabs/aws-sdk-rust). Here is my code
```rust
mod service_config;
// ...

const HOST: &str = "localhost";
const PORT: u32 = 4000;
const S3_HOST: &str = "http://localhost:9000";
const AWS_ACCESS_KEY_ID: &str = "minio";
const AWS_SECRET_ACCESS_KEY: &str = "minio123";

#[derive(Debug)]
struct AppState {
    s3: s3::Client,
}

impl AppState {
    fn new(client: s3::Client) -> Self {
        AppState { s3: client }
    }
}

struct CredentialsProvider;

impl ProvideCredentials for CredentialsProvider {
    fn provide_credentials(&self) -> Result<Credentials, CredentialsError> {
        Ok(Credentials::from_keys(
            AWS_ACCESS_KEY_ID,
            AWS_SECRET_ACCESS_KEY,
            None,
        ))
    }
}

#[actix_web::main]
async fn main() -> Result<(), Box<dyn Error>> {
    set_var("RUST_LOG", "debug,actix_web=debug");
    env_logger::init();
    let region = Region::new("eu-west-3");
    let s3_config = Config::builder()
        .region(region)
        .endpoint_resolver(Endpoint::immutable(Uri::from_static(S3_HOST)))
        .credentials_provider(CredentialsProvider)
        .build();
    let client = s3::Client::from_conf(s3_config);
    let app_state = web::Data::new(AppState::new(client));

    let (tx, rx) = mpsc::channel();

    thread::spawn(move || {
        let sys = System::new();
        let srv = HttpServer::new(move || {
            App::new()
                .wrap(Logger::new("%r -> [%s] took %Tms"))
                .app_data(app_state.clone())
                .configure(config) // config is a simple route that does nothing
        })
        .bind(format!("{}:{}", HOST, PORT))?
        .shutdown_timeout(5)
        .run();

        let _ = tx.send(srv);
        info!("🦀 running on port {} 🦀", PORT);
        sys.run()
    });

    let srv = rx.recv().unwrap();
    srv.await?;
    info!("gracefully shutdown");
    Ok(())
}
```
The versions are

- actix 4.0.0-beta.8
- aws-sdk-rust v0.0.9-alpha
- tokio ^1

## Expected Behavior
The app should work fine.

## Current Behavior
When I run the app there is a thread panic, see the logs
```
[2021-06-28T15:44:28Z DEBUG rustls::anchors] add_pem_file processed 128 valid and 0 invalid certs
[2021-06-28T15:44:28Z INFO  actix_server::builder] Starting 8 workers
[2021-06-28T15:44:28Z INFO  actix_server::builder] Starting "actix-web-service-[::1]:4000" service on [::1]:4000
[2021-06-28T15:44:28Z INFO  actix_server::builder] Starting "actix-web-service-127.0.0.1:4000" service on 127.0.0.1:4000
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/pierre/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/context.rs:28:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/main.rs:79:25
```
This is because there is a conflict between tokio version used by actix and aws-sdk ?

## Steps to Reproduce (for bugs)
clone the repo https://github.com/doums/archivur then
```
cargo run
```
observe

## Your Environment
GNU/Linux
```
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.53.0 (53cb7b09b 2021-06-17)`
```

**Comment by ibraheemdev** [comment]
4.0 beta's run tokio 1.0, 3.0 does not. You can also use a compatibility layer: https://docs.rs/tokio-compat-02/.

**Comment by doums** [comment]
Hi, I use actix in 4.0 beta and aws-sdk-rust in v0.0.9-alpha, both use tokio ^1. The bug was not due to an incompatible tokio version.  So I don't understood why you suggest me to use a compatibility layer.
Anyway, I asked the same question in aws-sdk-rust repo and a guy found that the panic was caused by the absence of a `sys.block_on` call. There is the code version that works now
```rust
mod service_config;
use actix_web::http::Uri;
use actix_web::middleware::Logger;
use actix_web::{rt::System, web, App, HttpServer};
use aws_auth::Credentials;
use aws_auth::CredentialsError;
use aws_auth::ProvideCredentials;
use log::info;
use s3::{Config, Region};
use smithy_http::endpoint::Endpoint;
use std::env::set_var;
use std::error::Error;
use std::sync::mpsc;
use std::thread;

use crate::service_config::config;

const HOST: &str = "localhost";
const PORT: u32 = 4000;
const S3_HOST: &str = "http://localhost:9000";
const AWS_ACCESS_KEY_ID: &str = "minio";
const AWS_SECRET_ACCESS_KEY: &str = "minio123";

#[derive(Debug)]
struct AppState {
    s3: s3::Client,
}

impl AppState {
    fn new(client: s3::Client) -> Self {
        AppState { s3: client }
    }
}

struct CredentialsProvider;

impl ProvideCredentials for CredentialsProvider {
    fn provide_credentials(&self) -> Result<Credentials, CredentialsError> {
        Ok(Credentials::from_keys(
            AWS_ACCESS_KEY_ID,
            AWS_SECRET_ACCESS_KEY,
            None,
        ))
    }
}

#[actix_web::main]
async fn main() -> Result<(), Box<dyn Error>> {
    set_var("RUST_LOG", "debug,actix_web=debug");
    env_logger::init();
    let region = Region::new("eu-west-3");
    let s3_config = Config::builder()
        .region(region)
        .endpoint_resolver(Endpoint::immutable(Uri::from_static(S3_HOST)))
        .credentials_provider(CredentialsProvider)
        .build();
    let client = s3::Client::from_conf(s3_config);
    let app_state = web::Data::new(AppState::new(client));

    let (tx, rx) = mpsc::channel();

    thread::spawn(move || {
        let sys = System::new();
        sys.block_on(async {
            let srv = HttpServer::new(move || {
                App::new()
                    .wrap(Logger::new("%r -> [%s] took %Tms"))
                    .app_data(app_state.clone())
                    .configure(config)
            })
            .bind(format!("{}:{}", HOST, PORT))
            .unwrap()
            .shutdown_timeout(5)
            .run();

            let _ = tx.send(srv);
        });
        info!("🦀 archivur running on port {} 🦀", PORT);
        sys.run()
    });

    let srv = rx.recv().unwrap();
    srv.await?;
    info!("archivur gracefully shutdown");
    Ok(())
}
```

**Comment by ibraheemdev** [comment]
Ah, sorry, I guess I closed it too quickly as we get many similar questions from 3.0 users. Yes, you would have to call `block_on` to enter the tokio runtime context :+1:
