### ISSUE TITLE
examples/tls

### ISSUE THREAD

**Issue by AlbanMinassian** [actix/actix-web#26]
``cargo run`` ok but error when use
```
thread 'arbiter:"a097acc7-af55-43b7-ba0f-61b256b68092":"actor"' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidHeaderValueBytes(InvalidHeaderValue { _priv: () })', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by fafhrd91** [comment]
use this command:

```
RUST_BACKTRACE=full cargo run
```
and post backtrace

**Comment by AlbanMinassian** [comment]
```
TRACE:actix_web::middleware::logger: Access log format: %a %t "%r" %s %b "%{Referrer}i" "%{User-Agent}i" %T
TRACE:actix_web::middleware::logger: Access log format: %a %t "%r" %s %b "%{Referrer}i" "%{User-Agent}i" %T
TRACE:actix_web::middleware::logger: Access log format: %a %t "%r" %s %b "%{Referrer}i" "%{User-Agent}i" %T
INFO:actix_web::server: Starting 4 http workers
INFO:actix_web::server: Starting tls http server on 127.0.0.1:8443
Started http server: 127.0.0.1:8443
TRACE:actix_web::middleware::logger: Access log format: %a %t "%r" %s %b "%{Referrer}i" "%{User-Agent}i" %T
thread 'arbiter:"70278274-f35c-447a-8829-70586ba27a6c":"actor"' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidHeaderValueBytes(InvalidHeaderValue { _priv: () })', /checkout/src/libcore/result.rs:906:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:772
  11: <actix_web::h2writer::H2Writer as actix_web::h1writer::Writer>::start
             at /home/ami44/.cargo/git/checkouts/actix-web-02c803d355aed967/a166fc8/src/h2writer.rs:135
  12: <actix_web::pipeline::ProcessResponse<S, H>>::poll_io
             at /home/ami44/.cargo/git/checkouts/actix-web-02c803d355aed967/a166fc8/src/pipeline.rs:583
  13: <actix_web::pipeline::Pipeline<S, H> as actix_web::channel::HttpHandlerTask>::poll_io
             at /home/ami44/.cargo/git/checkouts/actix-web-02c803d355aed967/a166fc8/src/pipeline.rs:167
  14: <actix_web::h2::Http2<T, H>>::poll
             at /home/ami44/.cargo/git/checkouts/actix-web-02c803d355aed967/a166fc8/src/h2.rs:95
  15: <actix_web::h2::Http2<T, H>>::poll
             at /home/ami44/.cargo/git/checkouts/actix-web-02c803d355aed967/a166fc8/src/h2.rs:220
  16: <actix_web::channel::HttpChannel<T, H> as futures::future::Future>::poll
             at /home/ami44/.cargo/git/checkouts/actix-web-02c803d355aed967/a166fc8/src/channel.rs:112
  17: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /home/ami44/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/mod.rs:113
  18: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}
             at /home/ami44/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:288
  19: <futures::task_impl::Spawn<T>>::enter::{{closure}}
             at /home/ami44/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:362
  20: futures::task_impl::std::set
             at /home/ami44/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/std/mod.rs:78
  21: <futures::task_impl::Spawn<T>>::enter
             at /home/ami44/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:362
  22: <futures::task_impl::Spawn<T>>::poll_future_notify
             at /home/ami44/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:288
  23: tokio_core::reactor::Core::dispatch_task::{{closure}}
             at /home/ami44/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.11/src/reactor/mod.rs:356
  24: <scoped_tls::ScopedKey<T>>::set
             at /home/ami44/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:135
  25: tokio_core::reactor::Core::dispatch_task
             at /home/ami44/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.11/src/reactor/mod.rs:355
  26: tokio_core::reactor::Core::dispatch
             at /home/ami44/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.11/src/reactor/mod.rs:316
  27: tokio_core::reactor::Core::poll
             at /home/ami44/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.11/src/reactor/mod.rs:304
  28: tokio_core::reactor::Core::run
             at /home/ami44/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.11/src/reactor/mod.rs:241
  29: actix::arbiter::Arbiter::new::{{closure}}
             at /home/ami44/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.3.5/src/arbiter.rs:88

```

**Comment by fafhrd91** [comment]
fixed in master
