### ISSUE TITLE
awc not working inside #[tokio::main]

### ISSUE THREAD

**Issue by banditopazzo** [actix/actix-web#2679]
## Expected Behavior
awc working inside `#[tokio::main]`

## Current Behavior
panics
```
thread 'main' panicked at '`spawn_local` called from outside of a `task::LocalSet`', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/task/local.rs:307:18
```
but it not happens if inside `#[actix_web::main]`

## Steps to Reproduce (for bugs)
the simplest way is to run the example at [https://github.com/actix/actix-web/blob/master/awc/examples/client.rs](https://github.com/actix/actix-web/blob/master/awc/examples/client.rs)

## Your Environment
- Rust Version (I.e, output of `rustc -V`): `rustc 1.59.0 (9d1b2106e 2022-02-23)`
- Actix Web Version: `awc 3.0.0-beta.21`
- Dependencies:
```toml
[dependencies]
env_logger = "0.9.0"
awc = "3.0.0-beta.21"
tokio = {version = "1.17.0", features = ["full"]}
```

## Output with BACKTRACE
```
thread 'main' panicked at '`spawn_local` called from outside of a `task::LocalSet`', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/task/local.rs:307:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::panic_display
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/option.rs:1817:5
   5: core::option::Option<T>::expect
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/option.rs:692:21
   6: tokio::task::local::spawn_local_inner::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/task/local.rs:306:22
   7: tokio::macros::scoped_tls::ScopedKey<T>::with
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/scoped_tls.rs:72:13
   8: tokio::task::local::spawn_local_inner
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/task/local.rs:305:9
   9: tokio::task::local::spawn_local
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/task/local.rs:295:9
  10: actix_rt::spawn
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.6.0/src/lib.rs:207:5
  11: actix_http::date::DateService::new
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.1/src/date.rs:57:22
  12: actix_http::config::ServiceConfig::new
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.1/src/config.rs:52:27
  13: <actix_http::config::ServiceConfig as core::default::Default>::default
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.1/src/config.rs:27:9
  14: <actix_http::h1::client::ClientCodec as core::default::Default>::default
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.1/src/h1/client.rs:50:26
  15: awc::client::h1proto::send_request::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/awc-3.0.0-beta.21/src/client/h1proto.rs:66:38
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
  17: awc::client::connection::Connection<A,B>::send_request::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/awc-3.0.0-beta.21/src/client/connection.rs:262:67
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
  19: <awc::connect::ConnectRequestFuture<Fut,Io> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/awc-3.0.0-beta.21/src/connect.rs:158:46
  20: <awc::connect::ConnectRequestFuture<Fut,Io> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/awc-3.0.0-beta.21/src/connect.rs:155:17
  21: <awc::middleware::redirect::RedirectServiceFuture<S> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/awc-3.0.0-beta.21/src/middleware/redirect.rs:157:31
  22: <awc::sender::SendClientRequest as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/awc-3.0.0-beta.21/src/sender.rs:108:48
  23: rust_test::main::{{closure}}
             at ./src/main.rs:17:38
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
  25: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:54
  26: tokio::coop::with_budget::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  27: std::thread::local::LocalKey<T>::try_with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:412:16
  28: std::thread::local::LocalKey<T>::with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:388:9
  29: tokio::coop::with_budget
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  30: tokio::coop::budget
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  31: tokio::park::thread::CachedParkThread::block_on
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:31
  32: tokio::runtime::enter::Enter::block_on
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/enter.rs:151:13
  33: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/mod.rs:73:9
  34: tokio::runtime::Runtime::block_on
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/mod.rs:477:43
  35: rust_test::main
             at ./src/main.rs:26:5
  36: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by fakeshadow** [comment]
tokio macro starts a multi-threaded runtime and awc only use single thread runtime. You should use `actix_rt::main`.
This is working as intended and there is no plan to make it support multi-threaded tokio.
