### ISSUE TITLE
Use unwrap () in the request.rs to get a crash error

### ISSUE THREAD

**Issue by guoyucode** [actix/actix-web#2947]
```
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Option::unwrap()` on a `None` value', /xxx/actix-web-4.2.1/src/request.rs:148:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:775:21
   4: actix_web::request::HttpRequest::match_info_mut
             at /Users/my_user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.2.1/src/request.rs:148:14
   5: actix_web::service::ServiceRequest::match_info_mut
             at /Users/my_user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.2.1/src/service.rs:254:9
   6: <actix_web::service::ServiceRequest as actix_router::resource_path::Resource>::resource_path
             at /Users/my_user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.2.1/src/service.rs:344:9
   7: actix_router::resource::ResourceDef::capture_match_info_fn
             at /Users/my_user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-router-0.5.1/src/resource.rs:675:20
   8: actix_router::router::Router<T,U>::recognize_fn
             at /Users/my_user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-router-0.5.1/src/router.rs:55:16
   9: <actix_web::app_service::AppRouting as actix_service::Service<actix_web::service::ServiceRequest>>::call
             at /Users/my_user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.2.1/src/app_service.rs:308:19
  10: <core::cell::RefCell<S> as actix_service::Service<Req>>::call
             at /Users/my_user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-2.0.2/src/lib.rs:245:9
  11: <alloc::rc::Rc<S> as actix_service::Service<Req>>::call
             at /Users/my_user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-2.0.2/src/lib.rs:227:9
  12: <polaris::actix_web_middleware::token::AuthorizationTokenValidatorMiddleware<S> as actix_service::Service<actix_web::service::ServiceRequest>>::call::{{closure}}
             at ./src/actix_web_middleware/token.rs:83:20
```

**Comment by robjtede** [comment]
It is likely you have cloned the HttpRequest in a middleware before calling `service.call()`. This is not allowed in the current API.

**Comment by XX** [comment]
One possible solution is to use `Rc<S: Service>` in your own middleware structure. For example: https://github.com/actix/examples/blob/master/middleware/middleware/src/read_request_body.rs
