### ISSUE TITLE
SIGINT hanging

### ISSUE THREAD

**Issue by pka** [actix/actix-web#316]
My application is always hanging when stopping with Ctrl-C (actix-web + actix master).

Output:
```
2018-06-14 23:08:13.669 INFO Starting 4 http workers
2018-06-14 23:08:13.669 INFO Starting server on http://127.0.0.1:6767
...
^C2018-06-15 00:17:06.787 DEBUG loop process - 1 events, 0.000s
2018-06-15 00:17:06.787 INFO SIGINT received, exiting
2018-06-15 00:17:06.787 DEBUG loop process - 1 events, 0.000s
2018-06-15 00:17:06.788 DEBUG loop process - 1 events, 0.000s
2018-06-15 00:17:06.788 DEBUG loop process - 1 events, 0.000s
2018-06-15 00:17:06.788 DEBUG loop process - 0 events, 0.000s
2018-06-15 00:17:06.788 INFO Force shutdown http worker, 1 connections
2018-06-15 00:17:06.788 DEBUG loop process - 0 events, 0.000s
2018-06-15 00:17:06.787 DEBUG loop process - 1 events, 0.000s
2018-06-15 00:17:06.788 DEBUG loop process - 0 events, 0.000s
...
```

Init code:
```rust
actix::System::run(move || {
    HttpServer::new(move || {
        let config = config_from_args(&args);
        let mut service = service_from_args(&config, &args);
        /* ... */

        App::with_state(AppState{service, config})
            .middleware(middleware::Logger::default())
            .resource("/index.json", |r| r.method(Method::GET).a(mvt_metadata))
            /* ... */
    }).bind(&bind_addr)
        .expect("Can not start server on given IP/Port")
        .shutdown_timeout(3) // default: 30s
        .start();
});
```

Backtrace: [gdb.txt](https://github.com/actix/actix-web/files/2104023/gdb.txt)

**Comment by eddomuke** [comment]
maybe try running it like
let sys = system::new();
server::new();
sys.run();

**Comment by pka** [comment]
@eddomuke When starting like https://actix.rs/docs/server/, the application crashes in HttpServer.start() after issuing the following panic:

```
2018-06-15 00:58:37.814 TRACE Notifier::notify; id=0x7f7ce821c160
2018-06-15 00:58:37.814 TRACE submit to existing worker; idx=0; state=worker::State { lifecycle: Sleeping, is_pushed: true }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SpawnError { is_shutdown: true }', libcore/result.rs:945:5
2018-06-15 00:58:37.814 TRACE     -> wakeup; idx=0
```

**Comment by ghost** [comment]
if you can write the line that panics I can search the documentation and source code for the reason.

**Comment by pka** [comment]
```
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:72
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  10: tokio_executor::global::spawn
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.2/src/global.rs:128
  11: tokio::executor::spawn
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.7/src/executor/mod.rs:207
  12: actix::actor::Actor::create
             at /home/pi/.cargo/git/checkouts/actix-483f9bf6bacb882b/8800f08/src/actor.rs:159
  13: <actix_web::server::srv::HttpServer<H>>::start
             at /home/pi/.cargo/git/checkouts/actix-web-02c803d355aed967/c8528e8/src/server/srv.rs:461
  14: t_rex_webserver::server::webserver
             at t-rex-webserver/src/server.rs:393
  15: t_rex::main
             at src/main.rs:153
  16: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  17: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  18: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  19: std::rt::lang_start_internal
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  20: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  21: main
  22: __libc_start_main
  23: _start
```

**Comment by ghost** [comment]
I think [this](http://rust-lang-nursery.github.io/futures-rs/futures_core/executor/struct.SpawnError.html) is the error that is thrown. Your output says that `is_shutdown=true` so I think it might mean that the spawning of an Actor is failing because there is no system or the system has been shut down.

**Comment by eddomuke** [comment]
Oh sorry I what version of actix are you using. I can't find the Actix::System::run method you are using in your first post.

**Comment by daboross** [comment]
I'm running into the same problem as OP (the hanging, not the panic).


Minimal reproduction:

```rust
extern crate actix;
extern crate actix_web;

fn main() {
    actix::System::run(|| {
        actix_web::server::new(|| actix_web::App::new())
            .bind("127.0.0.1:8080")
            .unwrap()
            .start();
    });
}
```

Using actix https://github.com/actix/actix/commit/c298a65954ff9d14907e40b13f4e493bd2f80d19 and actix-web https://github.com/actix/actix-web/commit/566b16c1f748b014422faf0bafa77a916af5cb86.

When killed with CTRL+C / SIGINT, it will output that it has shutdown, but stay hanging.

```
[INFO][actix_web::server::srv] Starting 4 http workers
[INFO][actix_web::server::srv] Starting server on http://127.0.0.1:8080
^C[INFO][actix_web::server::srv] SIGINT received, exiting
[INFO][actix_web::server::worker] Shutting down http worker, 0 connections
[INFO][actix_web::server::worker] Shutting down http worker, 0 connections
```
It then hangs until I kill it with SIGKILL.

<details>
<summary>(code with logging here)</summary>

```rust
extern crate actix;
extern crate actix_web;
extern crate fern;
extern crate log;

fn main() {
    fern::Dispatch::new()
        .level(log::LevelFilter::Info)
        .format(|out, msg, record| {
            out.finish(format_args!(
                "[{}][{}] {}",
                record.level(),
                record.target(),
                msg
            ))
        })
        .chain(std::io::stdout())
        .apply()
        .unwrap();

    actix::System::run(|| {
        actix_web::server::new(|| {
            actix_web::App::new().middleware(actix_web::middleware::Logger::default())
        }).bind("127.0.0.1:8080")
            .unwrap()
            .start();
    });
}
```

</details>

Is there a way to get the actix system to properly shutdown after sigint has been received? I'm starting the system this way so I can run some tokio futures before starting actix-web.

**Comment by fafhrd91** [comment]
fixed in master

**Comment by daboross** [comment]
Thanks! :+1:

**Comment by pka** [comment]
Problem solved. Thanks @fafhrd91!
