### ISSUE TITLE
System is not running

### ISSUE THREAD

**Issue by GildedHonour** [actix/actix-web#358]
Exception in my project that's been running fine until recently:

```

   $ RUST_BACKTRACE=1 cargo run 

     Running `target/debug/main`
thread 'main' panicked at 'System is not running', /home/alex/.cargo/git/checkouts/actix-483f9bf6bacb882b/ad74429/src/system.rs:82:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:365
   6: actix::system::System::current::{{closure}}
             at /home/alex/.cargo/git/checkouts/actix-483f9bf6bacb882b/ad74429/src/system.rs:82
   7: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:290
   8: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:244
   9: actix::system::System::current
             at /home/alex/.cargo/git/checkouts/actix-483f9bf6bacb882b/ad74429/src/system.rs:80
  10: actix::arbiter::Arbiter::new
             at /home/alex/.cargo/git/checkouts/actix-483f9bf6bacb882b/ad74429/src/arbiter.rs:49
  11: actix::arbiter::Arbiter::start
             at /home/alex/.cargo/git/checkouts/actix-483f9bf6bacb882b/ad74429/src/arbiter.rs:176
  12: <actix_web::server::srv::HttpServer<H>>::start_workers
             at /home/alex/.cargo/git/checkouts/actix-web-02c803d355aed967/0be5448/src/server/srv.rs:359
  13: <actix_web::server::srv::HttpServer<H>>::start
             at /home/alex/.cargo/git/checkouts/actix-web-02c803d355aed967/0be5448/src/server/srv.rs:435
  14: main::main
             at src/main.rs:278
  15: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  18: std::rt::lang_start_internal
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  19: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  20: main
  21: __libc_start_main
  22: _start

```

and

```
actix = "0.6.1"
actix-web = { git = "https://github.com/actix/actix-web", version = "0.7.0-dev" }
```

**Comment by fafhrd91** [comment]
you need `actix="0.5"`
