### ISSUE TITLE
Direct access to http://127.0.0.1:8080 can cause a thread to panic without routing being set

### ISSUE THREAD

**Issue by gmg137** [actix/actix-web#452]
Direct access to http://127.0.0.1:8080 can cause a thread to crash without routing being set
![2018-08-07 19-22-47](https://user-images.githubusercontent.com/6460323/43773503-80728fc6-9a78-11e8-8a06-2a432c4d2820.png)

**Comment by DoumanAsh** [comment]
Can you please share full stack trace here as text?

**Comment by gmg137** [comment]
@DoumanAsh 
```
fn main() {
    ::std::env::set_var("RUST_LOG", "actix_web=info");
    ::std::env::set_var("RUST_BACKTRACE", "1");
    env_logger::init();
    let sys = actix::System::new("xy");
    let server = Arbiter::start(|_| ChatServer::default());

    server::new(move || {
        let state = WsChatSessionState {
            addr: server.clone(),
        };
        vec![
            App::new()
            // enable logger
            .middleware(middleware::Logger::default())
            .filter(pred::Header("G-TOKEN", TOKEN))
            .prefix("/api")
            ......
            .boxed(),
            App::with_state(state)
                .filter(pred::Header("G-TOKEN", TOKEN))
                .resource("/ws", |r| r.route().f(ws))
                .boxed(),
        ]
    }).bind("127.0.0.1:7878")
        .unwrap()
        .shutdown_timeout(3)
        .start();

    println!("Started http server: 127.0.0.1:7878");
    let _ = sys.run();
}

```

```
thread 'arbiter:0b3b3571-65fb-409f-b670-5bc01e256693:actor' panicked at 'assertion failed: self.remaining_mut() >= src.len()', /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bytes-0.4.9/src/bytes.rs:1490:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:445
   6: <bytes::bytes::BytesMut as bytes::buf::buf_mut::BufMut>::put_slice
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/actix-web-0.7.3/<panic macros>:3
   7: actix_web::server::helpers::write_status_line
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/actix-web-0.7.3/src/server/helpers.rs:52
   8: <actix_web::server::error::ServerError as actix_web::server::HttpHandlerTask>::poll_io
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/actix-web-0.7.3/src/server/error.rs:19
   9: <alloc::boxed::Box<actix_web::server::HttpHandlerTask + 'static> as actix_web::server::HttpHandlerTask>::poll_io
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/actix-web-0.7.3/src/server/mod.rs:161
  10: <actix_web::server::h1::EntryPipe<H>>::poll_io
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/actix-web-0.7.3/src/server/h1.rs:70
  11: <actix_web::server::h1::Http1<T, H>>::poll_handler
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/actix-web-0.7.3/src/server/h1.rs:246
  12: <actix_web::server::h1::Http1<T, H>>::poll
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/actix-web-0.7.3/src/server/h1.rs:164
  13: <actix_web::server::channel::HttpChannel<T, H> as futures::future::Future>::poll
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/actix-web-0.7.3/src/server/channel.rs:111
  14: <actix_web::server::channel::HttpChannel<T, H> as futures::future::Future>::poll
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/actix-web-0.7.3/src/server/channel.rs:173
  15: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/futures-0.1.23/src/future/mod.rs:113
  16: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/futures-0.1.23/src/task_impl/mod.rs:289
  17: <futures::task_impl::Spawn<T>>::enter::{{closure}}
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/futures-0.1.23/src/task_impl/mod.rs:363
  18: futures::task_impl::std::set
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/futures-0.1.23/src/task_impl/std/mod.rs:78
  19: <futures::task_impl::Spawn<T>>::enter
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/futures-0.1.23/src/task_impl/mod.rs:363
  20: <futures::task_impl::Spawn<T>>::poll_future_notify
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/futures-0.1.23/src/task_impl/mod.rs:289
  21: <tokio::executor::current_thread::scheduler::Scheduled<'a, U>>::tick
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.7/src/executor/current_thread/scheduler.rs:352
  22: <tokio::executor::current_thread::scheduler::Scheduler<U>>::tick::{{closure}}
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.7/src/executor/current_thread/scheduler.rs:332
  23: <tokio::executor::current_thread::Borrow<'a, U>>::enter::{{closure}}::{{closure}}
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.7/src/executor/current_thread/mod.rs:762
  24: tokio::executor::current_thread::CurrentRunner::set_spawn
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.7/src/executor/current_thread/mod.rs:794
  25: <tokio::executor::current_thread::Borrow<'a, U>>::enter::{{closure}}
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.7/src/executor/current_thread/mod.rs:761
  26: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:294
  27: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:248
  28: <tokio::executor::current_thread::Borrow<'a, U>>::enter
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.7/src/executor/current_thread/mod.rs:760
  29: <tokio::executor::current_thread::scheduler::Scheduler<U>>::tick
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.7/src/executor/current_thread/scheduler.rs:332
  30: <tokio::executor::current_thread::Entered<'a, P>>::tick
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.7/src/executor/current_thread/mod.rs:611
  31: <tokio::executor::current_thread::Entered<'a, P>>::block_on
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.7/src/executor/current_thread/mod.rs:495
  32: tokio::runtime::current_thread::runtime::Runtime::block_on::{{closure}}
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.7/src/runtime/current_thread/runtime.rs:138
  33: tokio::runtime::current_thread::runtime::Runtime::enter::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.7/src/runtime/current_thread/runtime.rs:179
  34: tokio_executor::global::with_default::{{closure}}
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-executor-0.1.2/src/global.rs:176
  35: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:294
  36: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:248
  37: tokio_executor::global::with_default
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-executor-0.1.2/src/global.rs:150
  38: tokio::runtime::current_thread::runtime::Runtime::enter::{{closure}}::{{closure}}::{{closure}}
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.7/src/runtime/current_thread/runtime.rs:177
  39: tokio_timer::timer::handle::with_default::{{closure}}
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-timer-0.2.4/src/timer/handle.rs:64
  40: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:294
  41: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:248
  42: tokio_timer::timer::handle::with_default
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-timer-0.2.4/src/timer/handle.rs:56
  43: tokio::runtime::current_thread::runtime::Runtime::enter::{{closure}}::{{closure}}
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.7/src/runtime/current_thread/runtime.rs:170
  44: tokio_timer::clock::clock::with_default::{{closure}}
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-timer-0.2.4/src/clock/clock.rs:136
  45: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:294
  46: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:248
  47: tokio_timer::clock::clock::with_default
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-timer-0.2.4/src/clock/clock.rs:119
  48: tokio::runtime::current_thread::runtime::Runtime::enter::{{closure}}
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.7/src/runtime/current_thread/runtime.rs:169
  49: tokio_reactor::with_default::{{closure}}
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-reactor-0.1.2/src/lib.rs:231
  50: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:294
  51: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:248
  52: tokio_reactor::with_default
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-reactor-0.1.2/src/lib.rs:214
  53: tokio::runtime::current_thread::runtime::Runtime::enter
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.7/src/runtime/current_thread/runtime.rs:168
  54: tokio::runtime::current_thread::runtime::Runtime::block_on
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-0.1.7/src/runtime/current_thread/runtime.rs:136
  55: actix::arbiter::Arbiter::new_with_builder::{{closure}}
             at /home/gmg/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/actix-0.7.3/src/arbiter.rs:114
ERROR 2018-08-07T11:54:06Z: actix_web::server::accept: No workers
ERROR 2018-08-07T11:54:06Z: actix_web::server::srv: Worker has died 0, restarting
ERROR 2018-08-07T11:54:06Z: actix_web::server::srv: Worker has died 1, restarting
```

**Comment by DoumanAsh** [comment]
@gmg137 By any chance do you have your code open on repository? I have troubles to reproduce the panic

**Comment by hoodie** [comment]
@fafhrd91 I see this again in `actix-web 1.0.0-alpha.2` after calling [`WebsocketContext::text`](https://github.com/hoodie/signaler/blob/master/server/src/session.rs#L82)

```
thread 'actix-rt:worker:0' panicked at 'assertion failed: self.remaining_mut() >= src.len()', /home/hendrik/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.4.12/src/bytes.rs:1542:9
stack backtrace:
   0:     0x56270038d623 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hf8722b0178fb1b63
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x5627003886c8 - std::sys_common::backtrace::_print::hc40139e5f1d656ee
                               at src/libstd/sys_common/backtrace.rs:70
   2:     0x56270038b8a2 - std::panicking::default_hook::{{closure}}::h993d43465919c16a
                               at src/libstd/sys_common/backtrace.rs:58
                               at src/libstd/panicking.rs:200
   3:     0x56270038b614 - std::panicking::default_hook::h73d2c2ec3d9ba5a4
                               at src/libstd/panicking.rs:215
   4:     0x56270038bfb0 - std::panicking::rust_panic_with_hook::h744417edfe714d72
                               at src/libstd/panicking.rs:478
   5:     0x5626fff41077 - std::panicking::begin_panic::h2bacae3c197daa34
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/panicking.rs:412
   6:     0x5626ffeefe4d - <bytes::bytes::BytesMut as bytes::buf::buf_mut::BufMut>::put_slice::h7a75e2dc5663de56
                               at /home/hendrik/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-0.1.0-alpha.2/<::std::macros::panic macros>:3
   7:     0x5626ffee7581 - actix_http::ws::frame::Parser::write_message::h3cc042412add9c3b
                               at /home/hendrik/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-0.1.0-alpha.2/src/ws/frame.rs:193
   8:     0x5626ffee1570 - <actix_http::ws::codec::Codec as tokio_io::codec::encoder::Encoder>::encode::hfe9c871a778c142a
                               at /home/hendrik/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-0.1.0-alpha.2/src/ws/codec.rs:80
   9:     0x5626ffd19610 - <actix_web_actors::ws::WebsocketContextFut<A> as futures::stream::Stream>::poll::h5d35d739994e38e2
                               at /home/hendrik/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-actors-1.0.0-alpha.2/src/ws.rs:317
  10:     0x5626ffd5c8e7 - <actix_http::body::BodyStream<S, E> as actix_http::body::MessageBody>::poll_next::h978ce28b92362069
                               at /home/hendrik/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-0.1.0-alpha.2/src/body.rs:362
  11:     0x5626ffef13d5 - <actix_http::body::Body as actix_http::body::MessageBody>::poll_next::h3aefbd5382dd61b5

...
```

**Update:**
actually I had put a `trace!` behind `ctx.text(...)` and it was still able to trace that. not sure if that was just because it is async though.
Sorry for the lack of details, my current master is a good reproducer though

**Comment by fafhrd91** [comment]
@hoodie could you try actix-http master?

**Comment by hoodie** [comment]
can't reproduce with that version. seems you allocated enough space :grin:

**Comment by fafhrd91** [comment]
good. i will release alpha3 during this week
