### ISSUE TITLE
actix-rt:worker:1' panicked at 'already borrowed: BorrowMutError

### ISSUE THREAD

**Issue by xleyba** [actix/actix-web#793]
Hi

I am receiving the following error from an application that is using the client to send a GET to another service.

```[2019-04-23T13:39:49Z DEBUG bankr::handlers] Calling endpoint: http://127.0.0.1:9596/echo/javier
[2019-04-23T13:39:49Z DEBUG tokio_reactor] dropping I/O source: 4
[2019-04-23T13:39:49Z DEBUG tokio_reactor] adding I/O source: 838860804
thread '[2019-04-23T13:39:49Z DEBUG tokio_reactor::registration] scheduling Read for: 4
actix-rt:worker:1' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:997:5
[2019-04-23T13:39:49Z DEBUG tokio_reactor] adding I/O source: 843055105
[2019-04-23T13:39:49Z DEBUG tokio_reactor::registration] scheduling Read for: 1
[2019-04-23T13:39:49Z DEBUG tokio_reactor::registration] scheduling Read for: 4
[2019-04-23T13:39:49Z DEBUG bankr::handlers] Calling endpoint: http://127.0.0.1:9596/echo/javier
thread 'actix-rt:worker:0' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:997:5
stack backtrace:
   0:        0x1088e08a3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h7a8ad671c8651583
   1:        0x1088dbbf2 - std::sys_common::backtrace::_print::hcedf791e47ec936f
   2:        0x1088de966 - std::panicking::default_hook::{{closure}}::hee8806e2e3721c77
   3:        0x1088de671 - std::panicking::default_hook::h81a57c37f2bd6229
   4:        0x1088df0df - std::panicking::rust_panic_with_hook::hff16cb2217d41f10
   5:        0x1088dec0c - std::panicking::continue_panic_fmt::hf5ffe4ff8aa540e7
   6:        0x1088deaf8 - rust_begin_unwind
   7:        0x1088f2631 - core::panicking::panic_fmt::h086d308925f17445
   8:        0x1085c6f80 - core::result::unwrap_failed::hc80b4c325e086bce
   9:        0x1085dba54 - <actix_http::client::pool::ConnectionPool<T, Io> as actix_service::Service>::call::hfd1745181796452d
  10:        0x1085aebeb - <actix_http::client::connector::connect_impl::InnerConnector<T, Io> as actix_service::Service>::call::h2f1e2d87a17e799d
  11:        0x1085f2c8a - <awc::connect::ConnectorWrapper<T> as awc::connect::Connect>::send_request::h1bb186b87173e4a2
  12:        0x1085d1b39 - awc::request::ClientRequest::send::ha99f40e961581622
  13:        0x108504795 - actix_web::handler::m::<impl actix_web::handler::AsyncFactory<(A, B), Res> for Func>::call::h6a5d7560f56d682d
  14:        0x10853ec19 - <actix_web::handler::ExtractResponse<T, S> as futures::future::Future>::poll::hf4daaede5ac7ad8e
  15:        0x10856aa9a - <actix_web::route::RouteServiceWrapper<T> as actix_service::Service>::call::h9062f891f06c12cf
  16:        0x10859fb17 - <actix_web::resource::ResourceService as actix_service::Service>::call::h6226b0caa4d5d115
  17:        0x108520abb - <actix_service::boxed::ServiceWrapper<T> as actix_service::Service>::call::h96c1681b90a91032
  18:        0x10859132e - <actix_web::app_service::AppRouting as actix_service::Service>::call::ha8a07d952b21c831
  19:        0x108554601 - <actix_web::app_service::AppInitService<T, B> as actix_service::Service>::call::h2c17aeb73f6ca0f4
  20:        0x108534850 - <actix_http::h1::dispatcher::InnerDispatcher<T, S, B, X, U>>::handle_request::h3ab52c8b23d7082e
  21:        0x1085310a1 - <actix_http::h1::dispatcher::InnerDispatcher<T, S, B, X, U>>::poll_request::h9827603389c1e656
  22:        0x10855eda1 - <actix_http::h1::dispatcher::Dispatcher<T, S, B, X, U> as futures::future::Future>::poll::hf3dd61ddb5679832
  23:        0x10856056c - <actix_http::service::HttpServiceHandlerResponse<T, S, B, X, U> as futures::future::Future>::poll::hdf565ae5f73422c3
  24:        0x10856129f - <actix_http::service::HttpServiceHandlerResponse<T, S, B, X, U> as futures::future::Future>::poll::hdf565ae5f73422c3
  25:        0x1084f79b1 - <futures::future::chain::Chain<A, B, C>>::poll::hd1e17dee99c5ab68
  26:        0x10867985c - futures::task_impl::std::set::h43e88200cd726419
  27:        0x10867a2ee - <futures::task_impl::Spawn<T>>::poll_future_notify::h438025163b3b92f1
  28:        0x10866d473 - tokio_current_thread::CurrentRunner::set_spawn::hd9e020ea510d13ec
  29:        0x10866a234 - <tokio_current_thread::scheduler::Scheduler<U>>::tick::h376ee5d4b20d5512
  30:        0x10866f6a9 - <tokio_current_thread::Entered<'a, P>>::block_on::ha15211ce5c468fb4
  31:        0x1086663e3 - <std::thread::local::LocalKey<T>>::with::he86a359278a15e93
  32:        0x108665573 - <std::thread::local::LocalKey<T>>::with::h8e0d262002eee79a
  33:        0x1086661fb - <std::thread::local::LocalKey<T>>::with::he6ce617daecce2c0
  34:        0x108664444 - <std::thread::local::LocalKey<T>>::with::h4704ad83ab2a00a4
  35:        0x1086721c1 - actix_rt::runtime::Runtime::block_on::h445698c67820f3a7
  36:        0x10866be86 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha15cfabdc9652993
  37:        0x108672921 - std::panicking::try::do_call::h4e7b537c203ab67a
  38:        0x1088e30fe - __rust_maybe_catch_panic
  39:        0x10866ec02 - <F as alloc::boxed::FnBox<A>>::call_box::hfff8a664111885ef
  40:        0x1088e260b - std::sys::unix::thread::Thread::new::thread_start::h20d3ef41b46f13b9
  41:     0x7fff5bbc82ea - _pthread_body
  42:     0x7fff5bbcb248 - _pthread_start
stack backtrace:
   0:        0x1088e08a3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h7a8ad671c8651583
   1:        0x1088dbbf2 - std::sys_common::backtrace::_print::hcedf791e47ec936f
[2019-04-23T13:39:49Z DEBUG tokio_reactor] dropping I/O source: 0
Panic in Arbiter thread, shutting down system.
   2:        0x1088de966 - std::panicking::default_hook::{{closure}}::hee8806e2e3721c77
   3:        0x1088de671 - std::panicking::default_hook::h81a57c37f2bd6229
   4:        0x1088df0df - std::panicking::rust_panic_with_hook::hff16cb2217d41f10
   5:        0x1088dec0c - std::panicking::continue_panic_fmt::hf5ffe4ff8aa540e7
   6:        0x1088deaf8 - rust_begin_unwind
[2019-04-23T13:39:49Z DEBUG tokio_reactor] dropping I/O source: 2
   7:        0x1088f2631 - core::panicking::panic_fmt::h086d308925f17445[2019-04-23T13:39:49Z DEBUG tokio_reactor] dropping I/O source: 4

   8:        0x1085c6f80 - core::result::unwrap_failed::hc80b4c325e086bce
   9:        0x1085dba54 - <actix_http::client::pool::ConnectionPool<T, Io> as actix_service::Service>::call::hfd1745181796452d
  10:        0x1085aebeb - <actix_http::client::connector::connect_impl::InnerConnector<T, Io> as actix_service::Service>::call::h2f1e2d87a17e799d
  11:        0x1085f2c8a - <awc::connect::ConnectorWrapper<T> as awc::connect::Connect>::send_request::h1bb186b87173e4a2
  12:        0x1085d1b39 - awc::request::ClientRequest::send::ha99f40e961581622
  13:        0x108504795 - actix_web::handler::m::<impl actix_web::handler::AsyncFactory<(A, B), Res> for Func>::call::h6a5d7560f56d682d
  14:        0x10853ec19 - <actix_web::handler::ExtractResponse<T, S> as futures::future::Future>::poll::hf4daaede5ac7ad8e
  15:        0x10856aa9a - <actix_web::route::RouteServiceWrapper<T> as actix_service::Service>::call::h9062f891f06c12cf
  16:        0x10859fb17 - <actix_web::resource::ResourceService as actix_service::Service>::call::h6226b0caa4d5d115
  17:        0x108520abb - <actix_service::boxed::ServiceWrapper<T> as actix_service::Service>::call::h96c1681b90a91032
  18:        0x10859132e - <actix_web::app_service::AppRouting as actix_service::Service>::call::ha8a07d952b21c831
  19:        0x108554601 - <actix_web::app_service::AppInitService<T, B> as actix_service::Service>::call::h2c17aeb73f6ca0f4
  20:        0x108534850 - <actix_http::h1::dispatcher::InnerDispatcher<T, S, B, X, U>>::handle_request::h3ab52c8b23d7082e
  21:        0x1085310a1 - <actix_http::h1::dispatcher::InnerDispatcher<T, S, B, X, U>>::poll_request::h9827603389c1e656
  22:        0x10855eda1 - <actix_http::h1::dispatcher::Dispatcher<T, S, B, X, U> as futures::future::Future>::poll::hf3dd61ddb5679832
  23:        0x10856056c - <actix_http::service::HttpServiceHandlerResponse<T, S, B, X, U> as futures::future::Future>::poll::hdf565ae5f73422c3
  24:        0x10856129f - <actix_http::service::HttpServiceHandlerResponse<T, S, B, X, U> as futures::future::Future>::poll::hdf565ae5f73422c3
  25:        0x1084f79b1 - <futures::future::chain::Chain<A, B, C>>::poll::hd1e17dee99c5ab68
  26:        0x10867985c - futures::task_impl::std::set::h43e88200cd726419
  27:        0x10867a2ee - <futures::task_impl::Spawn<T>>::poll_future_notify::h438025163b3b92f1
  28:        0x10866d473 - tokio_current_thread::CurrentRunner::set_spawn::hd9e020ea510d13ec
  29:        0x10866a234 - <tokio_current_thread::scheduler::Scheduler<U>>::tick::h376ee5d4b20d5512
  30:        0x10866f6a9 - <tokio_current_thread::Entered<'a, P>>::block_on::ha15211ce5c468fb4
  31:        0x1086663e3 - <std::thread::local::LocalKey<T>>::with::he86a359278a15e93
  32:        0x108665573 - <std::thread::local::LocalKey<T>>::with::h8e0d262002eee79a
  33:        0x1086661fb - <std::thread::local::LocalKey<T>>::with::he6ce617daecce2c0
  34:        0x108664444 - <std::thread::local::LocalKey<T>>::with::h4704ad83ab2a00a4
  35:        0x1086721c1 - actix_rt::runtime::Runtime::block_on::h445698c67820f3a7
  36:        0x10866be86 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha15cfabdc9652993
  37:        0x108672921 - std::panicking::try::do_call::h4e7b537c203ab67a
  38:        0x1088e30fe - __rust_maybe_catch_panic
  39:        0x10866ec02 - <F as alloc::boxed::FnBox<A>>::call_box::hfff8a664111885ef
  40:        0x1088e260b - std::sys::unix::thread::Thread::new::thread_start::h20d3ef41b46f13b9
  41:     0x7fff5bbc82ea - _pthread_body
  42:     0x7fff5bbcb248 - _pthread_start
[2019-04-23T13:39:49Z DEBUG tokio_reactor] dropping I/O source: 4
Panic in Arbiter thread, shutting down system.
[2019-04-23T13:39:49Z DEBUG tokio_reactor] dropping I/O source: 1`
```
----------------

The call to the handler is here (in ain.rs):

```
#[derive(Deserialize, Debug)]
struct ConfigCalledService {
    client_url: String,
}

pub struct Parameters {
    pub client: Client,
    pub c_endpoint: String,
}

fn config_called_service() -> String {
    match envy::prefixed("BANK_").from_env::<ConfigCalledService>() {
      Ok(config) => {
          info!("Client URL set to: {}", config.client_url.to_string());
          config.client_url
      },
      Err(error) => {
          error!("Error with env var CLIENT_URL {}", error);
          info!("Client URL set to {} - default value", DEFAULT_CLIENT_URL.to_string());
          DEFAULT_CLIENT_URL.to_string()
      }
   }
}

fn main() {

let endpoint = config_called_service(); 

HttpServer::new(
        move || App::new()
            //.data({Client::default(), endpoint})
            .data(Parameters{
                client: Client::default(), 
                c_endpoint: endpoint.clone(),
            })
            .service(
                web::resource("/")
                    .route(web::get().to(index))
            ) // end service
            .service(
                web::resource("/echo/{message}")
                .route(web::get().to_async(echo_handler))
            ) // end hello service            
    ) // end http server
    .workers(workers)
    .bind(format!("127.0.0.1:{}", port))?
    .run()
```

And the handler is in handler.rs 

```
// echo handler
pub fn echo_handler(parameters: web::Data<Parameters>, msg: Path<Echo>) -> 
    impl Future<Item = HttpResponse, Error = ()> {

    let mut endpoint = parameters.c_endpoint.to_string();
    endpoint.push_str(&"/echo/".to_string());
    endpoint.push_str(&msg.message);
    debug!("Calling endpoint: {}", endpoint);

    parameters.client.get(endpoint)   // <- Create request builder
            .header("User-Agent", "Actix-web")
            //.finish().unwrap()
            .send()                               // <- Send http request
            .map_err(|err| {
                error!("error 1 = {:?}", err);
            })
            //.map_err(Error::from)
            .and_then(|mut response| {
                    response.body().and_then( |body| {
                        debug!("Received from endpoint: {}", str::from_utf8(&body).unwrap());
                        Ok(HttpResponse::Ok().body(body))
                    }).map_err(|err| {
                        error!("error 2 = {:?}", err);
                    })
                //}).map_err(|_| ())
            }).map_err(|err| {
                 error!("error 3 = {:?}", err);
            })
}
```

Is it a bug in Actix? Is it something that I should fix in my code?

Thanks in advance

**Comment by fafhrd91** [comment]
actix-http=0.1.2 released with fix

**Comment by fafhrd91** [comment]
thanks for report!
