### ISSUE TITLE
Broken after rebuild

### ISSUE THREAD

**Issue by FXTi** [actix/actix-web#902]
I'm using actix-web 0.7. And I just rebuild my project on another machine with a newly install stable toolchains.

It says:
```
thread 'arbiter:ef38f2e6-36a5-4929-a5a0-02f456fd9cbb:actix-net-worker-3' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Executor(EnterError { reason: "attempted to run an executor while another executor is already running" }), "http://www.cumt.edu.cn/")', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:212
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:382
   8: rust_begin_unwind
             at src/libstd/panicking.rs:309
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at /rustc/5eeb567a27eba18420a620ca7d0c007e29d8bc0c/src/libcore/macros.rs:18
  11: core::result::Result<T,E>::unwrap
             at /rustc/5eeb567a27eba18420a620ca7d0c007e29d8bc0c/src/libcore/result.rs:800
  12: cumtlobby_backend::news::get_headpic_handler
             at src/news.rs:34
```

And in `src/new.rs:34` is requesting a web page with reqwest, no additional arguments.

`attempted to run an executor while another executor is already running` error makes me so confused...

**Comment by fafhrd91** [comment]
It is your code or reqwest. Last 0.7 was released 2 months ago

**Comment by FXTi** [comment]
`src/news.rs:34` is my code, I called reqwest in there.

**Comment by fafhrd91** [comment]
I don't know what reqwest does. in any case I don't see how actix-web could cause this problem

**Comment by Txuritan** [comment]
I think reqwest is attempting to start a tokio runtime inside of actix's, you can use actix-web's build-in client instead.

**Comment by FXTi** [comment]
Problem found, it's reqwest 0.9.18, the version before it is okay.

I'll just stay at 0.9.17. This issue can be closed. It's not actix's problem.

@Txuritan you maybe right, but I don't have time to check it. Sorry for that.
