### ISSUE TITLE
Build fails on windows due to dependency on ring

### ISSUE THREAD

**Issue by dougxwok2** [actix/actix-web#907]
see https://github.com/briansmith/ring/issues/829

Cargo.toml:

```
[package]
name = "service"
version = "0.1.0"
authors = [""]
edition = "2018"

[[bin]]
path = "bin/service.rs"
name = "textnode"

[dependencies]
actix-web = "1.0"
```

cargo build:

```
cargo.exe build --color=always
   Compiling rand_core v0.4.0
   Compiling cfg-if v0.1.9
   Compiling winapi v0.2.8
   Compiling stable_deref_trait v1.1.1
   Compiling lazy_static v1.3.0
   Compiling smallvec v0.6.9
   Compiling scopeguard v0.3.3
   Compiling fnv v1.0.6
   Compiling slab v0.4.2
   Compiling matches v0.1.8
   Compiling encoding_index_tests v0.1.4
   Compiling futures v0.1.27
   Compiling rustc-demangle v0.1.15
   Compiling percent-encoding v1.0.1
   Compiling widestring v0.4.0
   Compiling scopeguard v1.0.0
   Compiling linked-hash-map v0.5.2
   Compiling quick-error v1.2.2
   Compiling either v1.5.2
   Compiling ucd-util v0.1.3
   Compiling itoa v0.4.4
   Compiling dtoa v0.4.4
   Compiling spin v0.5.0
   Compiling utf8-ranges v1.0.3
   Compiling indexmap v1.0.2
   Compiling untrusted v0.6.2
   Compiling hashbrown v0.3.1
   Compiling copyless v0.1.3
   Compiling language-tags v0.2.2
   Compiling sha1 v0.6.0
   Compiling log v0.4.6
   Compiling owning_ref v0.4.0
   Compiling crossbeam-utils v0.6.5
   Compiling thread_local v0.3.6
   Compiling unicode-bidi v0.3.4
   Compiling encoding-index-tradchinese v1.20141219.5
   Compiling encoding-index-japanese v1.20141219.5
   Compiling encoding-index-korean v1.20141219.5
   Compiling encoding-index-simpchinese v1.20141219.5
   Compiling encoding-index-singlebyte v1.20141219.5
   Compiling unicode-normalization v0.1.8
   Compiling lock_api v0.2.0
   Compiling rand_core v0.3.1
   Compiling lru-cache v0.1.2
   Compiling regex-syntax v0.6.7
   Compiling winapi v0.3.7
   Compiling byteorder v1.3.2
   Compiling libc v0.2.58
   Compiling ring v0.14.6
   Compiling lock_api v0.1.5
   Compiling memchr v2.2.0
error: failed to run custom build command for `ring v0.14.6`
process didn't exit successfully: `C:\Applications\dev\work-snippets\now\notebook\services\textnode-service\target\debug\build\ring-669acebded536063\build-script-build` (exit code: 101)
--- stdout
=::: ::\
ALLUSERSPROFILE: C:\ProgramData
APPDATA: C:\Users\d0D\AppData\Roaming
CARGO: \\?\C:\Users\d0D\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin\cargo.exe
CARGO_CFG_DEBUG_ASSERTIONS: 
CARGO_CFG_PROC_MACRO: 
CARGO_CFG_TARGET_ARCH: x86_64
CARGO_CFG_TARGET_ENDIAN: little
CARGO_CFG_TARGET_ENV: msvc
CARGO_CFG_TARGET_FAMILY: windows
CARGO_CFG_TARGET_FEATURE: fxsr,sse,sse2
CARGO_CFG_TARGET_OS: windows
CARGO_CFG_TARGET_POINTER_WIDTH: 64
CARGO_CFG_TARGET_VENDOR: pc
CARGO_CFG_WINDOWS: 
CARGO_FEATURE_DEFAULT: 1
CARGO_FEATURE_DEV_URANDOM_FALLBACK: 1
CARGO_FEATURE_USE_HEAP: 1
CARGO_HOME: C:\Applications\rust\.cargo
CARGO_MAKEFLAGS: --jobserver-fds=__rust_jobserver_semaphore_3572428603 --jobserver-auth=__rust_jobserver_semaphore_3572428603
CARGO_MANIFEST_DIR: C:\Applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6
CARGO_MANIFEST_LINKS: ring-asm
CARGO_PKG_AUTHORS: Brian Smith <brian@briansmith.org>
CARGO_PKG_DESCRIPTION: Safe, fast, small crypto using Rust.
CARGO_PKG_HOMEPAGE: 
CARGO_PKG_NAME: ring
CARGO_PKG_REPOSITORY: https://github.com/briansmith/ring
CARGO_PKG_VERSION: 0.14.6
CARGO_PKG_VERSION_MAJOR: 0
CARGO_PKG_VERSION_MINOR: 14
CARGO_PKG_VERSION_PATCH: 6
CARGO_PKG_VERSION_PRE: 
COMMONPROGRAMFILES: C:\Program Files\Common Files
COMMONPROGRAMFILES(X86): C:\Program Files (x86)\Common Files
COMMONPROGRAMW6432: C:\Program Files\Common Files
COMPUTERNAME: RAC-45356
COMSPEC: C:\WINDOWS\system32\cmd.exe
DEBUG: true
DRIVERDATA: C:\Windows\System32\Drivers\DriverData
DTEXECPATH: C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn
FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING: Default
HOME: C:/Users/d0D/
HOMEDRIVE: C:
HOMEPATH: \Users\d0D
HOST: x86_64-pc-windows-msvc
HTTP_PROXY: http://d0d:Snootborksatrobots.5@proxy.rac.com.au:8080/
LD_LIBRARY_PATH: C:\Users\d0D\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib
LOCALAPPDATA: C:\Users\d0D\AppData\Local
LOGONSERVER: \\DCB-DC2012-P003
NUMBER_OF_PROCESSORS: 8
NUM_JOBS: 8
ONEDRIVE: C:\Users\d0D\OneDrive - RACWA
ONEDRIVECOMMERCIAL: C:\Users\d0D\OneDrive - RACWA
OPT_LEVEL: 0
OS: Windows_NT
OUT_DIR: C:\Applications\dev\work-snippets\now\notebook\services\textnode-service\target\debug\build\ring-7f8077d125f4de1f\out
PATH: C:\Applications\dev\work-snippets\now\notebook\services\textnode-service\target\debug\deps;C:\Users\d0D\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin;C:\Applications\rust\.cargo\bin;C:\Users\d0D\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\app\d0d\product\11.2.0\client_2\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\app\d0d\product\11.2.0\client_1\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\sbt\bin;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\PrivateAssemblies\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\HashiCorp\Vagrant\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\TortoiseSVN\bin;C:/Applications/rust/.cargo\bin;C:\Users\d0D\AppData\Local\Continuum\anaconda3;C:\Users\d0D\AppData\Local\Continuum\anaconda3\Library\mingw-w64\bin;C:\Users\d0D\AppData\Local\Continuum\anaconda3\Library\usr\bin;C:\Users\d0D\AppData\Local\Continuum\anaconda3\Library\bin;C:\Users\d0D\AppData\Local\Continuum\anaconda3\Scripts;C:\Users\d0D\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\d0D\AppData\Local\Programs\Python\Python37\;C:\Users\d0D\.cargo\bin;C:\Oracle\instantclient_12_1;C:\Users\d0D\AppData\Local\Microsoft\WindowsApps;C:\Users\d0D\AppData\Roaming\npm;C:\Users\d0D\AppData\Local\Programs\Fiddler;C:\Users\d0D\.dotnet\tools
PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE: AMD64
PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
PROCESSOR_LEVEL: 6
PROCESSOR_REVISION: 8e0a
PROFILE: debug
PROGRAMDATA: C:\ProgramData
PROGRAMFILES: C:\Program Files
PROGRAMFILES(X86): C:\Program Files (x86)
PROGRAMW6432: C:\Program Files
PSMODULEPATH: C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\PowerShell\Modules\
PUBLIC: C:\Users\Public
RUSTC: rustc
RUSTDOC: rustdoc
RUSTUP_HOME: C:\Users\d0D\.rustup
RUSTUP_TOOLCHAIN: stable-x86_64-pc-windows-msvc
RUST_BACKTRACE: short
RUST_RECURSION_COUNT: 1
SBT_HOME: C:\Program Files (x86)\sbt\
SESSIONNAME: Console
SYSTEMDRIVE: C:
SYSTEMROOT: C:\WINDOWS
TARGET: x86_64-pc-windows-msvc
TEMP: C:\Users\d0D\AppData\Local\Temp
TERM: ansi
TMP: C:\Users\d0D\AppData\Local\Temp
TNS_ADMIN: C:\app\d0d\product\11.2.0\client_2\network\admin
UATDATA: C:\WINDOWS\CCM\UATData\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77
USERDNSDOMAIN: RAC.COM.AU
USERDOMAIN: RAC
USERDOMAIN_ROAMINGPROFILE: RAC
USERNAME: d0d
USERPROFILE: C:\Users\d0D
VS110COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
WINDIR: C:\WINDOWS
WIX: C:\Program Files (x86)\WiX Toolset v3.11\
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-pc-windows-msvc")
CC_x86_64-pc-windows-msvc = None
CC_x86_64_pc_windows_msvc = None
HOST_CC = None
CC = None
CFLAGS_x86_64-pc-windows-msvc = None
CFLAGS_x86_64_pc_windows_msvc = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
DEBUG = Some("true")
running "C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\bin\\amd64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "include" "/W4" "/GS" "/Gy" "/EHsc" "/GR-" "/Zc:wchar_t" "/Zc:forScope" "/Zc:inline" "/Zc:rvalueCast" "/sdl" "/Wall" "/wd4127" "/wd4464" "/wd4514" "/wd4710" "/wd4711" "/wd4820" "/wd5045" "/Od" "/RTCsu" "-c" "/FoC:\\Applications\\dev\\work-snippets\\now\\notebook\\services\\textnode-service\\target\\debug\\build\\ring-7f8077d125f4de1f\\out\\block.obj" "crypto/block.c"
block.c
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(206) : warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(206) : error C2054: expected '(' to follow 'inline'
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(206) : error C2085: 'constant_time_msb_w' : not in formal parameter list
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(206) : error C2143: syntax error : missing ';' before '{'
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(211) : warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(211) : error C2054: expected '(' to follow 'inline'
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(211) : error C2085: 'constant_time_is_zero_w' : not in formal parameter list
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(211) : error C2143: syntax error : missing ';' before '{'
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(226) : warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(226) : error C2054: expected '(' to follow 'inline'
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(226) : error C2085: 'constant_time_is_nonzero_w' : not in formal parameter list
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(226) : error C2143: syntax error : missing ';' before '{'
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(231) : warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(231) : error C2054: expected '(' to follow 'inline'
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(232) : error C2085: 'constant_time_eq_w' : not in formal parameter list
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(232) : error C2143: syntax error : missing ';' before '{'
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(239) : warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(239) : error C2054: expected '(' to follow 'inline'
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(241) : error C2085: 'constant_time_select_w' : not in formal parameter list
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(241) : error C2143: syntax error : missing ';' before '{'
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(266) : warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(266) : error C2054: expected '(' to follow 'inline'
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(266) : error C2085: 'from_be_u32_ptr' : not in formal parameter list
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(266) : error C2143: syntax error : missing ';' before '{'
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(276) : warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(276) : error C2054: expected '(' to follow 'inline'
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(276) : error C2085: 'to_be_u32_ptr' : not in formal parameter list
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(276) : error C2143: syntax error : missing ';' before '{'
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(285) : warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(285) : error C2054: expected '(' to follow 'inline'
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(285) : error C2085: 'to_be_u64_ptr' : not in formal parameter list
c:\applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\crypto\internal.h(285) : error C2143: syntax error : missing ';' before '{'

--- stderr
cl : Command line warning D9014 : invalid value '5045' for '/wd'; assuming '4999'
cl : Command line warning D9002 : ignoring unknown option '/Zc:inline'
cl : Command line warning D9002 : ignoring unknown option '/Zc:rvalueCast'
thread 'main' panicked at 'execution failed', C:\Applications\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.14.6\build.rs:638:9
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys\windows\backtrace\mod.rs:95
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys\windows\backtrace\mod.rs:82
   2: std::sys_common::backtrace::_print
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::print
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\sys_common\backtrace.rs:59
   4: std::panicking::default_hook::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:197
   5: std::panicking::default_hook
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:474
   7: std::panicking::begin_panic<str*>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libstd\panicking.rs:408
   8: build_script_build::run_command
             at .\build.rs:638
   9: build_script_build::compile
             at .\build.rs:515
  10: build_script_build::build_library::{{closure}}
             at .\build.rs:453
  11: core::ops::function::impls::{{impl}}::call_once<(std::path::PathBuf*),closure>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\ops\function.rs:279
  12: core::option::Option<std::path::PathBuf*>::map<std::path::PathBuf*,alloc::string::String,mut closure*>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\option.rs:414
  13: core::iter::adapters::{{impl}}::next<alloc::string::String,core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure>,closure>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\iter\adapters\mod.rs:568
  14: alloc::vec::Vec<alloc::string::String>::extend_desugared<alloc::string::String,core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure>, closure>>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\liballoc\vec.rs:1929
  15: alloc::vec::{{impl}}::spec_extend<alloc::string::String,core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure>, closure>>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\liballoc\vec.rs:1826
  16: alloc::vec::{{impl}}::from_iter<alloc::string::String,core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure>, closure>>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\liballoc\vec.rs:1821
  17: alloc::vec::{{impl}}::from_iter<alloc::string::String,core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure>, closure>>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\liballoc\vec.rs:1721
  18: core::iter::traits::iterator::Iterator::collect<core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::chain::Chain<core::slice::Iter<std::path::PathBuf>, core::slice::Iter<std::path::PathBuf>>, closure>, closure>,alloc::vec::Vec<alloc::string::String>>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\iter\traits\iterator.rs:1465
  19: build_script_build::build_library
             at .\build.rs:449
  20: build_script_build::build_c_code::{{closure}}
             at .\build.rs:426
  21: core::iter::traits::iterator::Iterator::for_each::{{closure}}<core::slice::Iter<(str*, slice<std::path::PathBuf>*, slice<std::path::PathBuf>*)>,closure>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\iter\traits\iterator.rs:604
  22: core::slice::{{impl}}::fold<(str*, slice<std::path::PathBuf>*, slice<std::path::PathBuf>*),(),closure>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\slice\mod.rs:3150
  23: core::iter::traits::iterator::Iterator::for_each<core::slice::Iter<(str*, slice<std::path::PathBuf>*, slice<std::path::PathBuf>*)>,closure>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\iter\traits\iterator.rs:604
  24: build_script_build::build_c_code
             at .\build.rs:424
  25: build_script_build::ring_build_rs_main
             at .\build.rs:294
  26: build_script_build::main
             at .\build.rs:256
  27: std::rt::lang_start::{{closure}}<()>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libstd\rt.rs:64
  28: std::rt::lang_start_internal::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\rt.rs:49
  29: std::panicking::try::do_call<closure,i32>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:293
  30: panic_unwind::__rust_maybe_catch_panic
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libpanic_unwind\lib.rs:87
  31: std::panicking::try
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panicking.rs:272
  32: std::panic::catch_unwind
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\panic.rs:388
  33: std::rt::lang_start_internal
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\/src\libstd\rt.rs:48
  34: std::rt::lang_start<()>
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libstd\rt.rs:64
  35: main
  36: __tmainCRTStartup
             at f:\dd\vctools\crt_bld\self_64_amd64\crt\src\crtexe.c:536
  37: BaseThreadInitThunk
  38: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
error: build failed

Process finished with exit code 101
```

I know this is an issue with ring, not actix-web, but I see there is another closed ticket about removing the dependency on ring from this crate.

All I can do is continue to voice my support for removing your dependency on ring.

In the meanwhile, I will leave this here for others to find. Note that unlike the other tickets lodged regarding this, I have a valid and up to date version of MSVC installed and have no problem building other crates.

**Comment by pythoneer** [comment]
I am a little bit surprised ... i thought ring was removed for 1.0? At least the [issue](https://github.com/actix/actix-web/issues/741) and the [PR](https://github.com/actix/actix-web/pull/895) made me believe that this was removed?

**Comment by fafhrd91** [comment]
ring is disabled by default now
