### ISSUE TITLE
Segmentation fault (core dumped) when a mass of requests 

### ISSUE THREAD

**Issue by littleboss** [actix/actix-web#962]
`#0  0x00007f2e72859459 in __memcpy_ssse3_back () from /lib64/libc.so.6
#1  0x000055f36e603ca5 in _$LT$bytes..bytes..BytesMut$u20$as$u20$bytes..buf..buf_mut..BufMut$GT$::put_slice::hcbe12d6c87258e7f ()
#2  0x000055f36e51821b in actix_http::h1::encoder::TransferEncoding::encode::hb67177aa1a5039bf ()
#3  0x000055f36e515cff in _$LT$actix_http..h1..codec..Codec$u20$as$u20$tokio_io..codec..encoder..Encoder$GT$::encode::hfab0f59c9f4cddc7 ()
#4  0x000055f36e41f543 in actix_http::h1::dispatcher::InnerDispatcher$LT$T$C$S$C$B$C$X$C$U$GT$::poll_response::hd6922318d1d9ce48 ()
#5  0x000055f36e42e140 in _$LT$actix_http..h1..dispatcher..Dispatcher$LT$T$C$S$C$B$C$X$C$U$GT$$u20$as$u20$futures..future..Future$GT$::poll::h505f3f1f26a47a9b ()
#6  0x000055f36e430bb0 in _$LT$actix_http..service..HttpServiceHandlerResponse$LT$T$C$S$C$B$C$X$C$U$GT$$u20$as$u20$futures..future..Future$GT$::poll::ha1ff4ed0a3cd35f3 ()
#7  0x000055f36e431bc4 in _$LT$actix_http..service..HttpServiceHandlerResponse$LT$T$C$S$C$B$C$X$C$U$GT$$u20$as$u20$futures..future..Future$GT$::poll::ha1ff4ed0a3cd35f3 ()
#8  0x000055f36e4480f2 in futures::future::chain::Chain$LT$A$C$B$C$C$GT$::poll::h877c3617e53ad9fe ()
#9  0x000055f36e4f8c02 in futures::task_impl::std::set::hb287ad12547ab80a ()
#10 0x000055f36e505f56 in futures::task_impl::Spawn$LT$T$GT$::poll_future_notify::h96ff96a0732e9ab1 ()
#11 0x000055f36e5097a4 in tokio_current_thread::CurrentRunner::set_spawn::h52c6ab801f1b85b0 ()
#12 0x000055f36e50915a in tokio_current_thread::scheduler::Scheduler$LT$U$GT$::tick::hfd7bdf40e51fcd37 ()
#13 0x000055f36e509bba in tokio_current_thread::Entered$LT$P$GT$::block_on::h4426de6729ec5c53 ()
#14 0x000055f36e4fe5a8 in std::thread::local::LocalKey$LT$T$GT$::with::h06d70f7be1972c0e ()
#15 0x000055f36e500fd5 in std::thread::local::LocalKey$LT$T$GT$::with::hf4a887fcd2b2316d ()
#16 0x000055f36e4fec7f in std::thread::local::LocalKey$LT$T$GT$::with::h339a7391c58707e2 ()
#17 0x000055f36e4ff542 in std::thread::local::LocalKey$LT$T$GT$::with::h7712520ffceedfc3 ()
#18 0x000055f36e4f74c0 in actix_rt::runtime::Runtime::block_on::h5e36de314571d69b ()
#19 0x000055f36e506da8 in std::sys_common::backtrace::__rust_begin_short_backtrace::h3b42f2eb7b176955 ()
#20 0x000055f36e4f8649 in std::panicking::try::do_call::h997b1199b0f30d5b ()
#21 0x000055f36e618f0a in __rust_maybe_catch_panic () at src/libpanic_unwind/lib.rs:87
#22 0x000055f36e50be44 in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::hfb95236b9dccc3a5 ()
#23 0x000055f36e60752f in call_once<(),FnBox<()>> () at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
#24 0x000055f36e618350 in call_once<(),alloc::boxed::Box<FnBox<()>>> () at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/boxed.rs:702
#25 start_thread () at src/libstd/sys_common/thread.rs:14
#26 thread_start () at src/libstd/sys/unix/thread.rs:80
#27 0x00007f2e72cefe25 in start_thread () from /lib64/libpthread.so.0
#28 0x00007f2e72803bad in clone () from /lib64/libc.so.6`

**Comment by littleboss** [comment]
because of unsafe code  in router, sorry, close issue
