### ISSUE TITLE
Testing with 1.0 App with data errors with System is not running

### ISSUE THREAD

**Issue by nishtahir** [actix/actix-web#963]
Going by the docs here https://docs.rs/actix-web/1.0.3/actix_web/test/fn.init_service.html

```
#[test]
fn test_init_service() {
    use actix_service::Service;
    use actix_web::test;
    use actix_web::{http::StatusCode, web, App, HttpResponse};
    use dotenv::dotenv;

    dotenv().ok();
    let mut app = test::init_service(
        App::new()
            .data(create_app_state())
            .wrap(Logger::default())
            .wrap(middleware::NormalizePath)
            .configure(routes),
    );

    // Create request object
    let req = test::TestRequest::with_uri("/test").to_request();

    // Execute application
    let resp = test::block_on(app.call(req)).unwrap();
    assert_eq!(resp.status(), StatusCode::OK);
}
```

The implementation behind the created state bassed in as Data is a sync arbiter

```
        let addr = SyncArbiter::start(4, move || {
            DbExecutor::new(
               // R2D2 connection pool
            )
        });
```

Running the test fails with 

```
test app::test_init_service ... FAILED

failures:

---- app::test_init_service stdout ----
thread 'app::test_init_service' panicked at 'System is not running', /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.3/src/system.rs:78:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:209
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: std::panicking::begin_panic
             at /rustc/9a90d03ad171856dc016c2dcc19292ec49a8a26f/src/libstd/panicking.rs:409
   8: actix_rt::system::System::current::{{closure}}
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.3/src/system.rs:78
   9: std::thread::local::LocalKey<T>::try_with
             at /rustc/9a90d03ad171856dc016c2dcc19292ec49a8a26f/src/libstd/thread/local.rs:257
  10: std::thread::local::LocalKey<T>::with
             at /rustc/9a90d03ad171856dc016c2dcc19292ec49a8a26f/src/libstd/thread/local.rs:234
  11: actix_rt::system::System::current
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-0.2.3/src/system.rs:76
  12: actix::sync::SyncArbiter<A>::start
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.8.3/src/sync.rs:117
  13: server::data::AppState::new
             at server/src/data/mod.rs:27
  14: server::app::create_app_state
             at server/src/app.rs:47
  15: server::app::test_init_service
             at server/src/app.rs:75
  16: server::app::test_init_service::{{closure}}
             at server/src/app.rs:66
  17: core::ops::function::FnOnce::call_once
             at /rustc/9a90d03ad171856dc016c2dcc19292ec49a8a26f/src/libcore/ops/function.rs:231
  18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/9a90d03ad171856dc016c2dcc19292ec49a8a26f/src/liballoc/boxed.rs:746
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  20: std::panicking::try
             at /rustc/9a90d03ad171856dc016c2dcc19292ec49a8a26f/src/libstd/panicking.rs:273
  21: std::panic::catch_unwind
             at /rustc/9a90d03ad171856dc016c2dcc19292ec49a8a26f/src/libstd/panic.rs:388
  22: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1466
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    app::test_init_service
```

**Comment by cetra3** [comment]
If `create_app_state()` is called outside of the `test::block_on` this may fail as there is no `System` running when you start the SyncArbiter.

**Comment by fafhrd91** [comment]
is this ticket still relevant?

**Comment by fafhrd91** [comment]
closing as no activity

**Comment by stepankuzmin** [comment]
Hi everyone! I came across the same problem. I have a `mock_state` function

```rust
fn mock_state(
    table_sources: Option<TableSources>,
    function_sources: Option<FunctionSources>,
) -> State {
    let conn_string: String = env::var("DATABASE_URL").unwrap();
    let pool = setup_connection_pool(&conn_string, None).unwrap();

    let db = SyncArbiter::start(3, move || DBActor(pool.clone()));
    let coordinator: Addr<_> = CoordinatorActor::default().start();

    let table_sources = Rc::new(RefCell::new(table_sources));
    let function_sources = Rc::new(RefCell::new(function_sources));

    State {
        db: db.clone(),
        coordinator: coordinator.clone(),
        table_sources,
        function_sources,
        watch_mode: false,
    }
}
```

Is it a correct way to run a system before creating an app instance?

```rust
#[test]
fn test_get_table_sources_ok() {
    let _ = actix_rt::System::new("server");

    let mut app = test::init_service(
        App::new()
            .data(mock_state(mock_table_sources(), None))
            .configure(router),
    );

    let req = test::TestRequest::get().uri("/index.json").to_request();

    let resp = test::block_on(app.call(req)).unwrap();
    assert!(resp.status().is_success());
}
```

This works for me, but I'm not sure is it the right way to do it. Maybe I should create a system in my `mock_state` function?

**Comment by fafhrd91** [comment]
@stepankuzmin use `test::run_on()` instead of System::new()

**Comment by stepankuzmin** [comment]
Thanks for reply, @fafhrd91! I've tried to instantiate an app in `test::run_on` like so:

```rust
#[test]
fn test_get_table_source_tile_ok() {
    let future = test::run_on(|| {
        let mut app = test::init_service(
            App::new()
                .data(mock_state(mock_table_sources(), None))
                .configure(router),
        );

        let req = test::TestRequest::get()
            .uri("/public.table_source/0/0/0.pbf")
            .to_request();

        app.call(req)
    });

    let resp = test::block_on(future).unwrap();
    assert!(resp.status().is_success());
}
```

But I'm getting `thread 'server::tests::test_get_table_source_tile_ok' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:1084:5`

Am I missing something?

**Comment by fafhrd91** [comment]
you need to use run_on only with `mock_state()`

**Comment by stepankuzmin** [comment]
Oh, I got it, thanks! This works for me!

```rust
#[test]
fn test_get_table_sources_ok() {
    let state = test::run_on(|| mock_state(mock_table_sources(), None));

    let mut app = test::init_service(App::new().data(state).configure(router));

    let req = test::TestRequest::get().uri("/index.json").to_request();

    let resp = test::block_on(app.call(req)).unwrap();
    assert!(resp.status().is_success());
}
```

**Comment by nishtahir** [comment]
Would it be worth putting together some documentation/tutorials on how to write tests/how to write testable code with actix_web?

**Comment by fafhrd91** [comment]
@nishtahir good idea
